### ISSUE TITLE
Update and restart not executing

### ISSUE THREAD

**Issue by dodspunkare** [defold/editor2-issues#1003]
### Expected behaviour
I expected Defold to update and restart when I clicked "update and restart"

### Actual behaviour
Nothing happens and log says:

2017-06-15 12:25:16.322 92476 [JavaFX Application Thread] INFO  editor.updater - {:line 31, :message "update installation requested"}
2017-06-15 12:25:16.354 92508 [JavaFX Application Thread] INFO  com.defold.editor.Updater - copying C:\Users\Mattias\AppData\Local\Temp\6940062944233592432\54135838953860468.tmp -> C:\Program Files\Defold\packages\defold-725ed5e0d8e7483fbd5d5ca4368eee17ff489490.jar
2017-06-15 12:25:16.357 92511 [JavaFX Application Thread] DEBUG editor.updater - {:line 52, :message "update installation failed"}
java.io.FileNotFoundException: C:\Program Files\Defold\packages\defold-725ed5e0d8e7483fbd5d5ca4368eee17ff489490.jar (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1139)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at com.defold.editor.Updater$PendingUpdate.copyFile(Updater.java:46)
	at com.defold.editor.Updater$PendingUpdate.apply(Updater.java:51)
	at com.defold.editor.Updater$PendingUpdate.install(Updater.java:60)
	at editor.updater$ask_update_and_restart_BANG_.invokeStatic(updater.clj:48)
	at editor.updater$install_pending_update_check_BANG_$tick_fn__65629$fn__65630.invoke(updater.clj:59)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

### Steps to reproduce
Click "update and restart" next time it pops up.

<hr/>

<table>
<tr><td>Defold version</td><td>1.2.106</td></tr>
<tr><td>Defold sha</td><td>0ece1dbff284dd289088b29cea8e0dadac235960</td></tr>
<tr><td>Build time</td><td>2017-06-09T17:43:11.153892</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<table>

**Comment by erikangelin-king** [comment]
So you get this repeatedly now? Do you have several instances of the editor running?

**Comment by dodspunkare** [comment]
I always only have one instance running (as far as I know).

Yes I get it constantly, with somewhat regular intervals.

**Comment by dodspunkare** [comment]
I tried moving my Defold folder to my Users folder instead of Program Files. It seems to work with update and restart now.

I don't know if you guys have installation instructions on where to put Defold. Maybe have some popup when trying to update that tells the user that folder placement could be an issue would be helpful.

@erikangelin-king
@RagnarSvenssonKing

**Comment by erikangelin-king** [comment]
Great you got it running! The proper solution is probably a real installer :) But yes, instructions is a good idea.
