### ISSUE TITLE
Creating a tilemap causes VertexBuffer error

### ISSUE THREAD

**Issue by thehiflyer** [defold/editor2-issues#1013]
### Expected behaviour
I tried to create a tilemap in an almost empty project and expected the map to be created and possible to edit.
### Actual behaviour
On selecting a name I get an error popup. The console shows the following: 
2017-06-19 10:00:51.325 ERROR default    editor.error-reporting - {:line 98}
java.lang.AssertionError: Assert failed: VertexBuffer must be flipped before use.
(flipped? vbuf)
	at editor.gl.vertex2$update_vbo.invokeStatic(vertex2.clj:246)
	at editor.gl.vertex2$make_vbo.invokeStatic(vertex2.clj:250)
	at editor.gl.vertex2$make_vbo.invoke(vertex2.clj:250)
	at editor.scene_cache$request_object_BANG_.invokeStatic(scene_cache.clj:28)
	at editor.gl.vertex2$request_vbo.invokeStatic(vertex2.clj:192)
	at editor.gl.vertex2$bind_vertex_buffer_with_shader_BANG_.invokeStatic(vertex2.clj:212)
	at editor.gl.vertex2.VertexBufferShaderLink.bind(vertex2.clj:229)
	at editor.tile_map$render_layer.invokeStatic(tile_map.clj:135)
	at editor.tile_map$render_layer.invoke(tile_map.clj:126)
	at editor.scene$render_nodes.invokeStatic(scene.clj:212)
	at editor.scene$batch_render.invokeStatic(scene.clj:240)
	at editor.scene$render_BANG_.invokeStatic(scene.clj:278)
	at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:704)
	at editor.scene$make_gl_pane_BANG_$fn__27089$fn__27090$fn__27095.invoke(scene.clj:781)
	at editor.ui$__GT_timer$fn__11267.invoke(ui.clj:1440)
	at editor.ui.proxy$javafx.animation.AnimationTimer$ff19274a.handle(Unknown Source)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$484(AnimationTimer.java:57)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)

### Steps to reproduce
Create an empty project, create a tile source, create a tilemap, observe error popup.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.104</td></tr>
<tr><td>Defold sha</td><td>7b2ef0aa2f657205c680ddded145b245e11a8ed7</td></tr>
<tr><td>Build time</td><td>2017-05-10T13:30:14.083400</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.11.2-041102-generic</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=9cd2fa76491a479197255c0d839082d9'>9cd2fa76491a479197255c0d839082d9</a></td></tr>
<table>

**Comment by ragnard-king** [comment]
Closing this as the issue had already been fixed in a later version.
