### ISSUE TITLE
Editor freezes if expand folder

### ISSUE THREAD

**Issue by leotada** [defold/editor2-issues#1183]
### Expected behaviour
Expand folder structure.
### Actual behaviour
On click expand main folder, freezes the editor.
### Steps to reproduce
Copy images to main/images folder, create new folder in main/images, move the images to new folder, come back to editor and expand the main folder.
<hr/>

<table>
<tr><td>Defold version</td><td>1.2.112</td></tr>
<tr><td>Defold sha</td><td>583cf637b91f7c57ee4c8f174eb3bc8aabb29913</td></tr>
<tr><td>Build time</td><td>2017-09-05T15:56:57.720030</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.12.9-300.fc26.x86_64</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>GPU</td><td>Gallium 0.4 on AMD POLARIS10 (DRM 3.15.0 / 4.12.9-300.fc26.x86_64, LLVM 4.0.0)</td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 17.1.7</td></tr>
<table>

### Log
```
2017-09-05 21:47:54.364 90510 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 98}
java.lang.NullPointerException: null
	at editor.app_view$refresh_app_title_BANG_.invokeStatic(app_view.clj:554)
	at editor.app_view$refresh_ui_BANG_.invokeStatic(app_view.clj:561)
	at editor.app_view$make_app_view$fn__37473.invoke(app_view.clj:611)
	at editor.ui$__GT_timer$fn__11858.invoke(ui.clj:1628)
	at editor.ui.proxy$javafx.animation.AnimationTimer$ff19274a.handle(Unknown Source)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$484(AnimationTimer.java:57)
	at java.security.AccessController.doPrivileged(Native Method)
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56)
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357)
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
2017-09-05 21:47:58.883 2084453 [Timer-0] DEBUG com.defold.editor.Start - checking for updat
```

**Comment by erikangelin-king** [comment]
@leotada Can't repro, is this still happening?

**Comment by leotada** [comment]
Yes, I tested now in other computer with Defold version 1.2.118.
You have to move the images to new folder using an external file explorer.

**Comment by erikangelin-king** [comment]
Thanks for reporting back @leotada! Can you give me some more specs, what linux distribution are you running? window manager?

**Comment by leotada** [comment]
Fedora Linux 27 x64 runing Wayland.
