### ISSUE TITLE
Opening main.collection in feature test project fails

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#120]
### Expected behaviour

Collection opened succesfully.
### Actual behaviour

Exception thrown:

```
java.lang.NullPointerException: null
        at clojure.lang.RT.floatCast(RT.java:1276) ~[clojure-1.8.0.jar:na]
        at editor.gl.vertex$put_float.invokeStatic(vertex.clj:43) ~[na:na]
        at editor.gl.vertex$put_float.invoke(vertex.clj:43) ~[na:na]
        at editor.mesh$eval71010$setter_fn__31198__auto____71012.invoke(mesh.clj:33) ~[na:na]
        at editor.gl.vertex.TransientVertexBuffer.assocN(vertex.clj:261) ~[na:na]
        at editor.gl.vertex.TransientVertexBuffer.conj(vertex.clj:276) ~[na:na]
        at clojure.core$conj_BANG_.invokeStatic(core.clj:3257) ~[clojure-1.8.0.jar:na]
        at clojure.core$conj_BANG_.invoke(core.clj:3249) ~[clojure-1.8.0.jar:na]
        at editor.mesh$component__GT_vb.invokeStatic(mesh.clj:138) ~[na:na]
        at editor.mesh$component__GT_vb.invoke(mesh.clj:128) ~[na:na]
        at editor.mesh$fn__71442.invokeStatic(mesh.clj:141) ~[na:na]
        at editor.mesh$fn__71442.invoke(mesh.clj:141) ~[na:na]
        at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[clojure-1.8.0.jar:na]
        at clojure.lang.AFn.applyTo(AFn.java:144) ~[clojure-1.8.0.jar:na]
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) ~[clojure-1.8.0.jar:na]
        at clojure.lang.RestFn.invoke(RestFn.java:408) ~[clojure-1.8.0.jar:na]
        at clojure.lang.Var.invoke(Var.java:379) ~[clojure-1.8.0.jar:na]
        at editor.mesh$MeshNode$behavior$vbs.invokeStatic(mesh.clj:141) ~[na:na]
        at editor.mesh$MeshNode$behavior$vbs.invoke(mesh.clj:141) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.NodeImpl.produce_value(node.clj:268) ~[na:na]
        at editor.mesh$MeshNode$behavior$scene.invokeStatic(mesh.clj:141) ~[na:na]
        at editor.mesh$MeshNode$behavior$scene.invoke(mesh.clj:141) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.NodeImpl.produce_value(node.clj:268) ~[na:na]
        at internal.node$pull_first_input_value.invokeStatic(node.clj:1093) ~[na:na]
        at internal.node$pull_first_input_value.invoke(node.clj:1088) ~[na:na]
        at editor.model$ModelNode$behavior$scene.invokeStatic(model.clj:90) ~[na:na]
        at editor.model$ModelNode$behavior$scene.invoke(model.clj:90) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.NodeImpl.produce_value(node.clj:268) ~[na:na]
        at internal.node$pull_first_input_value.invokeStatic(node.clj:1093) ~[na:na]
        at internal.node$pull_first_input_value.invoke(node.clj:1088) ~[na:na]
        at editor.game_object$ReferencedComponent$behavior$scene.invokeStatic(game_object.clj:143) ~[na:na]
        at editor.game_object$ReferencedComponent$behavior$scene.invoke(game_object.clj:143) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.NodeImpl.produce_value(node.clj:268) ~[na:na]
        at internal.node$pull_input_values$fn__15310.invoke(node.clj:1109) ~[na:na]
        at clojure.core$mapv$fn__6953.invoke(core.clj:6627) ~[clojure-1.8.0.jar:na]
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:341) ~[clojure-1.8.0.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6544) ~[clojure-1.8.0.jar:na]
        at clojure.core$mapv.invokeStatic(core.clj:6618) ~[clojure-1.8.0.jar:na]
        at clojure.core$mapv.invoke(core.clj:6618) ~[clojure-1.8.0.jar:na]
        at internal.node$pull_input_values.invokeStatic(node.clj:1107) ~[na:na]
        at internal.node$pull_input_values.invoke(node.clj:1104) ~[na:na]
        at editor.game_object$GameObjectNode$behavior$scene.invokeStatic(game_object.clj:278) ~[na:na]
        at editor.game_object$GameObjectNode$behavior$scene.invoke(game_object.clj:278) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.OverrideNode.produce_value(node.clj:1605) ~[na:na]
        at internal.node$pull_first_input_value.invokeStatic(node.clj:1093) ~[na:na]
        at internal.node$pull_first_input_value.invoke(node.clj:1088) ~[na:na]
        at editor.collection$ReferencedGOInstanceNode$behavior$scene.invokeStatic(collection.clj:262) ~[na:na]
        at editor.collection$ReferencedGOInstanceNode$behavior$scene.invoke(collection.clj:262) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.OverrideNode.produce_value(node.clj:1605) ~[na:na]
        at internal.node$pull_input_values$fn__15310.invoke(node.clj:1109) ~[na:na]
        at clojure.core$mapv$fn__6953.invoke(core.clj:6627) ~[clojure-1.8.0.jar:na]
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:341) ~[clojure-1.8.0.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6544) ~[clojure-1.8.0.jar:na]
        at clojure.core$mapv.invokeStatic(core.clj:6618) ~[clojure-1.8.0.jar:na]
        at clojure.core$mapv.invoke(core.clj:6618) ~[clojure-1.8.0.jar:na]
        at internal.node$pull_input_values.invokeStatic(node.clj:1107) ~[na:na]
        at internal.node$pull_input_values.invoke(node.clj:1104) ~[na:na]
        at editor.collection$CollectionNode$behavior$scene.invokeStatic(collection.clj:420) ~[na:na]
        at editor.collection$CollectionNode$behavior$scene.invoke(collection.clj:420) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.OverrideNode.produce_value(node.clj:1605) ~[na:na]
        at internal.node$pull_first_input_value.invokeStatic(node.clj:1093) ~[na:na]
        at internal.node$pull_first_input_value.invoke(node.clj:1088) ~[na:na]
        at editor.collection$CollectionInstanceNode$behavior$scene.invokeStatic(collection.clj:497) ~[na:na]
        at editor.collection$CollectionInstanceNode$behavior$scene.invoke(collection.clj:497) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.NodeImpl.produce_value(node.clj:268) ~[na:na]
        at internal.node$pull_input_values$fn__15310.invoke(node.clj:1109) ~[na:na]
        at clojure.core$mapv$fn__6953.invoke(core.clj:6627) ~[clojure-1.8.0.jar:na]
        at clojure.lang.PersistentVector.reduce(PersistentVector.java:341) ~[clojure-1.8.0.jar:na]
        at clojure.core$reduce.invokeStatic(core.clj:6544) ~[clojure-1.8.0.jar:na]
        at clojure.core$mapv.invokeStatic(core.clj:6618) ~[clojure-1.8.0.jar:na]
        at clojure.core$mapv.invoke(core.clj:6618) ~[clojure-1.8.0.jar:na]
        at internal.node$pull_input_values.invokeStatic(node.clj:1107) ~[na:na]
        at internal.node$pull_input_values.invoke(node.clj:1104) ~[na:na]
        at editor.collection$CollectionNode$behavior$scene.invokeStatic(collection.clj:420) ~[na:na]
        at editor.collection$CollectionNode$behavior$scene.invoke(collection.clj:420) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.NodeImpl.produce_value(node.clj:268) ~[na:na]
        at internal.node$pull_first_input_value.invokeStatic(node.clj:1093) ~[na:na]
        at internal.node$pull_first_input_value.invoke(node.clj:1088) ~[na:na]
        at editor.scene$SceneView$behavior$render_data.invokeStatic(scene.clj:405) ~[na:na]
        at editor.scene$SceneView$behavior$render_data.invoke(scene.clj:405) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.NodeImpl.produce_value(node.clj:268) ~[na:na]
        at editor.scene$SceneView$behavior$selected_renderables.invokeStatic(scene.clj:405) ~[na:na]
        at editor.scene$SceneView$behavior$selected_renderables.invoke(scene.clj:405) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.NodeImpl.produce_value(node.clj:268) ~[na:na]
        at editor.scene$SceneView$behavior$selected_aabb.invokeStatic(scene.clj:405) ~[na:na]
        at editor.scene$SceneView$behavior$selected_aabb.invoke(scene.clj:405) ~[na:na]
        at clojure.lang.Var.invoke(Var.java:383) ~[clojure-1.8.0.jar:na]
        at internal.node.NodeImpl.produce_value(node.clj:268) ~[na:na]
        at internal.node$node_value_STAR_.invokeStatic(node.clj:335) ~[na:na]
        at internal.node$node_value_STAR_.invoke(node.clj:330) ~[na:na]
        at internal.node$node_value.invokeStatic(node.clj:357) ~[na:na]
        at internal.node$node_value.invoke(node.clj:350) ~[na:na]
        at dynamo.graph$node_value.invokeStatic(graph.clj:742) ~[na:na]
        at dynamo.graph$node_value.invoke(graph.clj:712) ~[na:na]
        at dynamo.graph$node_value.invokeStatic(graph.clj:728) ~[na:na]
        at dynamo.graph$node_value.invoke(graph.clj:712) ~[na:na]
        at editor.scene$frame_selection.invokeStatic(scene.clj:517) ~[na:na]
        at editor.scene$frame_selection.invoke(scene.clj:516) ~[na:na]
        at editor.scene$make_gl_pane$fn__35841.invoke(scene.clj:655) ~[na:na]
        at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren(Unknown Source) ~[na:na]
        at javafx.scene.Parent.layout(Parent.java:1087) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Parent.layout(Parent.java:1093) ~[jfxrt.jar:na]
        at javafx.scene.Scene.doLayoutPass(Scene.java:552) ~[jfxrt.jar:na]
        at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397) ~[jfxrt.jar:na]
        at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355) ~[jfxrt.jar:na]
        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_101]
        at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354) ~[jfxrt.jar:na]
        at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381) ~[jfxrt.jar:na]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510) ~[jfxrt.jar:na]
        at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490) ~[jfxrt.jar:na]
        at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319) ~[jfxrt.jar:na]
        at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
```
### Steps to reproduce
1. Open feature test project.
2. Open `main.collection`.

<hr/>

Defold version: dev
Defold sha: 
Platform: Mac OS X 10.11.6 (x86_64)
Java version: 1.8.0_101-b13

**Comment by ragnard-king** [comment]
Possibly a good time to use new vertex buffers for models/meshes?

**Comment by ragnard-king** [comment]
Works now.
