### ISSUE TITLE
Editor refuses to open project

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1245]
Current editor build refuses to open this project as is.

https://github.com/subsoap/deffx

When this kind of thing happens the information needs to be directly presented to the user. Maybe a dialog which says "Could not open project. Open log folder? Yes / No"

Here is error when opening this project

```
2017-09-30 20:16:58.177 23432 [clojure-agent-send-off-pool-0] ERROR editor.ui - {:line 1550}
java.lang.Exception: Invalid setting line: <<<<<<< HEAD
	at editor.settings_core$parse_error.invokeStatic(settings_core.clj:39)
	at editor.settings_core$parse_settings$fn__455.invoke(settings_core.clj:48)
	at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:167)
	at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at editor.settings_core$parse_settings.invokeStatic(settings_core.clj:45)
	at editor.defold_project$read_dependencies.invokeStatic(defold_project.clj:533)
	at editor.defold_project$open_project_BANG_.invokeStatic(defold_project.clj:558)
	at editor.boot_open_project$open_project.invokeStatic(boot_open_project.clj:291)
	at editor.boot_open_project$open_project.invoke(boot_open_project.clj:289)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at editor.boot$open_project_with_progress_dialog$fn__97359.invoke(boot.clj:144)
	at editor.ui$modal_progress$fn__11746$fn__11751$fn__11752.invoke(ui.clj:1548)
	at editor.ui$modal_progress$fn__11746$fn__11751.invoke(ui.clj:1547)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2017-09-30 20:16:58.190 23445 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 98}
java.security.PrivilegedActionException: null
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.Exception: Invalid setting line: <<<<<<< HEAD
	at editor.settings_core$parse_error.invokeStatic(settings_core.clj:39)
	at editor.settings_core$parse_settings$fn__455.invoke(settings_core.clj:48)
	at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:167)
	at clojure.core.protocols$fn__6755.invoke(protocols.clj:124)
	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75)
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13)
	at clojure.core$reduce.invokeStatic(core.clj:6545)
	at editor.settings_core$parse_settings.invokeStatic(settings_core.clj:45)
	at editor.defold_project$read_dependencies.invokeStatic(defold_project.clj:533)
	at editor.defold_project$open_project_BANG_.invokeStatic(defold_project.clj:558)
	at editor.boot_open_project$open_project.invokeStatic(boot_open_project.clj:291)
	at editor.boot_open_project$open_project.invoke(boot_open_project.clj:289)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at editor.boot$open_project_with_progress_dialog$fn__97359.invoke(boot.clj:144)
	at editor.ui$modal_progress$fn__11746$fn__11751$fn__11752.invoke(ui.clj:1548)
	at editor.ui$modal_progress$fn__11746$fn__11751.invoke(ui.clj:1547)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	... 1 common frames omitted

```

**Comment by subsoap** [comment]
Fixed the bad game.project file, git messed up somewhere. Still need more information to user with errors like this.

**Comment by AGulev** [comment]
[game.project.zip](https://github.com/defold/editor2-issues/files/2729729/game.project.zip)
example of broken game.project file
