### ISSUE TITLE
OOM when opening project

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#15]
(reported by @gregor-king-gullwi)

Opening the project on Windows, results in an out of memory exception

```
2016-08-12 12:18:27.100 25089 [JavaFX Application Thread] ERROR editor.boot - {:line 158, :msg "uncaught exception"}
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3236) ~[na:1.8.0_45]
	at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118) ~[na:1.8.0_45]
	at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93) ~[na:1.8.0_45]
	at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153) ~[na:1.8.0_45]
	at editor.resource$read_zip_entry.invokeStatic(resource.clj:136) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.resource$load_zip.invokeStatic(resource.clj:150) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.resource$make_zip_tree.invokeStatic(resource.clj:159) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.resource_watch$make_library_zip_tree.invokeStatic(resource_watch.clj:27) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.resource_watch$make_library_snapshot.invokeStatic(resource_watch.clj:38) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.resource_watch$make_library_snapshot.invoke(resource_watch.clj:35) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core$partial$fn__4759.invoke(core.clj:2515) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core$map$fn__4785.invoke(core.clj:2646) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.lang.Cons.next(Cons.java:39) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.lang.RT.next(RT.java:688) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core$next__4341.invokeStatic(core.clj:64) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core.protocols$fn__6755.invokeStatic(protocols.clj:168) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core.protocols$fn__6755.invoke(protocols.clj:124) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core.protocols$fn__6710$G__6705__6719.invoke(protocols.clj:19) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core.protocols$fn__6736.invokeStatic(protocols.clj:75) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core.protocols$fn__6736.invoke(protocols.clj:75) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6545) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.resource_watch$combine_snapshots.invokeStatic(resource_watch.clj:84) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.resource_watch$make_snapshot.invokeStatic(resource_watch.clj:95) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:211) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.defold_project$open_project_BANG_.invokeStatic(defold_project.clj:745) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.boot_open_project$open_project.invokeStatic(boot_open_project.clj:240) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at editor.boot_open_project$open_project.invoke(boot_open_project.clj:238) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:160) ~[defold-5d66e7558c01d26cf5ff6250014ac2173acaf0b9.jar:na]
2
```

**Comment by RagnarSvenssonKing** [comment]
Fixed
