### ISSUE TITLE
Crashes on mac after opening project

### ISSUE THREAD

**Issue by olegtyshcneko** [defold/editor2-issues#1644]
When app is initializing I got following exception:
com.defold.editor.Start - failed to extract native libs
java.lang.UnsatisfiedLinkError: jogamp.common.jvm.JVMUtil.initialize(Ljava/nio/ByteBuffer;)Z
	at jogamp.common.jvm.JVMUtil.initialize(Native Method)
	at jogamp.common.jvm.JVMUtil.<clinit>(JVMUtil.java:58)
	at com.jogamp.common.os.Platform$1.run(Platform.java:320)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:287)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.defold.editor.Start.lambda$kickLoading$1(Start.java:136)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

After opening the app it crashes with following exception:
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at clojure.core$deref_future.invokeStatic(core.clj:2208)
	at clojure.core$future_call$reify__6962.deref(core.clj:6688)
	at clojure.core$deref.invokeStatic(core.clj:2228)
	at editor.boot$open_project_with_progress_dialog$fn__135538.invoke(boot.clj:148)
	at editor.ui$modal_progress$fn__11918$fn__11923$fn__11924.invoke(ui.clj:1610)
	at editor.ui$modal_progress$fn__11918$fn__11923.invoke(ui.clj:1609)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.jogamp.opengl.GLProfile

**Comment by erikangelin-king** [comment]
Hi @olegtyshcneko! We're trying to repro this. Does it happen every time? On what macos version? Where did you put the Defold application? Are you using the latest version, downloaded from the Dashboard?

**Comment by erikangelin-king** [comment]
Closing, please reopen if it's still an issue.
