### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1687]
This happened when editing GUI of a simple project. I don't remember the exact dialog which appeared but it had no report options. Here is relevant bit from log I think

```
2018-02-20 13:12:05.932 4208271 [JavaFX Application Thread] WARN  editor.app-view - {:line 481}
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at editor.engine$reboot.invokeStatic(engine.clj:69)
	at editor.app_view$reboot_engine.invokeStatic(app_view.clj:426)
	at editor.app_view$launch_built_project.invokeStatic(app_view.clj:473)
	at editor.app_view$build_handler$fn__44826$fn__44829.invoke(app_view.clj:515)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
2018-02-20 13:12:14.852 4217191 [JavaFX Application Thread] WARN  editor.app-view - {:line 481}
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
	at editor.engine$reboot.invokeStatic(engine.clj:69)
	at editor.app_view$reboot_engine.invokeStatic(app_view.clj:426)
	at editor.app_view$launch_built_project.invokeStatic(app_view.clj:473)
	at editor.app_view$build_handler$fn__44826$fn__44829.invoke(app_view.clj:515)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
```

Restarting editor allowed building again.

<hr/>

<table>
<tr><td>Build time</td><td>2018-02-20T13:20:55.242831</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>965412654cfd7cc7b81136666ecb731690b33553</td></tr>
<tr><td>Defold engine sha</td><td>9988355914f63362a4292c4827639f0187275e70</td></tr>
<tr><td>Defold version</td><td>1.2.121</td></tr>
<tr><td>GPU</td><td>GeForce GTX 750/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 390.65</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by subsoap** [comment]
Happened again, the dialog is "Build failed: build connection refused"

**Comment by erikangelin-king** [comment]
Hi @subsoap! The target selection was broken for a couple of weeks, resulting in us trying to connect either to localhost or to old engine instances. This looks like the type of error you would get. Has this happened again? We merged a fix about a week ago.
