### ISSUE TITLE
Build doesnt build and run the game due to missing main collection in game.project

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#174]
Not sure how the main collection was removed. Not manually by me. 

2016-11-10 11:21:29.687 166  [JavaFX Application Thread] DEBUG com.defold.editor.Start - automatic updates enabled
2016-11-10 11:21:30.828 1307 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\lib'
2016-11-10 11:21:30.833 1312 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/texc_shared.dll' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\lib\texc_shared.dll'
2016-11-10 11:21:30.866 1345 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/particle_shared.dll' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\lib\particle_shared.dll'
2016-11-10 11:21:30.877 1356 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/newt.dll' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\lib\newt.dll'
2016-11-10 11:21:30.879 1358 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/nativewindow_win32.dll' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\lib\nativewindow_win32.dll'
2016-11-10 11:21:30.882 1361 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/nativewindow_awt.dll' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\lib\nativewindow_awt.dll'
2016-11-10 11:21:30.886 1365 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/jogl_mobile.dll' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\lib\jogl_mobile.dll'
2016-11-10 11:21:30.892 1371 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/jogl_desktop.dll' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\lib\jogl_desktop.dll'
2016-11-10 11:21:30.901 1380 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/lib/gluegen-rt.dll' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\lib\gluegen-rt.dll'
2016-11-10 11:21:30.904 1383 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/bin/' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\bin'
2016-11-10 11:21:30.905 1384 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/bin/OpenAL32.dll' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\bin\OpenAL32.dll'
2016-11-10 11:21:30.908 1387 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/bin/luajit.exe' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\bin\luajit.exe'
2016-11-10 11:21:30.918 1397 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/bin/dmengine_release.exe' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\bin\dmengine_release.exe'
2016-11-10 11:21:31.003 1482 [Timer-0] DEBUG com.defold.editor.Start - checking for updates
2016-11-10 11:21:31.006 1485 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/x86-win32/bin/dmengine.exe' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\bin\dmengine.exe'
2016-11-10 11:21:31.133 1612 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit'
2016-11-10 11:21:31.135 1614 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/lj.supp' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\lj.supp'
2016-11-10 11:21:31.136 1615 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit'
2016-11-10 11:21:31.137 1616 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/vmdef.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\vmdef.lua'
2016-11-10 11:21:31.139 1618 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/v.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\v.lua'
2016-11-10 11:21:31.140 1619 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/dump.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\dump.lua'
2016-11-10 11:21:31.142 1621 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/dis_x86.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\dis_x86.lua'
2016-11-10 11:21:31.144 1623 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/dis_x64.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\dis_x64.lua'
2016-11-10 11:21:31.145 1624 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/dis_ppc.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\dis_ppc.lua'
2016-11-10 11:21:31.148 1627 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/dis_mipsel.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\dis_mipsel.lua'
2016-11-10 11:21:31.226 1705 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/dis_mips.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\dis_mips.lua'
2016-11-10 11:21:31.227 1706 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/dis_arm.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\dis_arm.lua'
2016-11-10 11:21:31.228 1707 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/bcsave.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\bcsave.lua'
2016-11-10 11:21:31.230 1709 [pool-2-thread-1] DEBUG com.defold.libs.ResourceUnpacker - unpacking '/_unpack/shared/luajit/jit/bc.lua' to 'C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633\luajit\jit\bc.lua'
2016-11-10 11:21:31.234 1713 [pool-2-thread-1] INFO  com.defold.libs.ResourceUnpacker - defold.unpack.path=C:\Users\SOFIA~1.HED\AppData\Local\Temp\defold-unpack2176126858606482633
2016-11-10 11:21:58.002 28481 [JavaFX Application Thread] ERROR editor.handler - {:line 47, :msg "handler :build in context :global failed at :run with message [java.lang.IllegalArgumentException: No implementation of method: :proj-path of protocol: #'editor.resource/Resource found for class: nil]"}
java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: No implementation of method: :proj-path of protocol: #'editor.resource/Resource found for class: nil
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[na:1.8.0_102]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[na:1.8.0_102]
	at clojure.core$deref_future.invokeStatic(core.clj:2208) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core$future_call$reify__6962.deref(core.clj:6688) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core$deref.invokeStatic(core.clj:2228) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.app_view$fn__34773$fnk34768_positional__34774.invoke(app_view.clj:249) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.app_view$fn__34773$fnk34768__34788$fn__34789.invoke(app_view.clj:245) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.app_view$fn__34773$fnk34768__34788.invoke(app_view.clj:245) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:45) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.handler$run.invokeStatic(handler.clj:65) [defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.ui$make_menu_command$fn__10601.invoke(ui.clj:676) [defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.ui$make_menu_command$reify__10603.handle(ui.clj:690) [defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) ~[jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) ~[jfxrt.jar:na]
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) ~[jfxrt.jar:na]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
Caused by: java.lang.IllegalArgumentException: No implementation of method: :proj-path of protocol: #'editor.resource/Resource found for class: nil
	at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.resource$fn__7866$G__7795__7871.invoke(resource.clj:18) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.game_project$build_game_project$fn__55643.invoke(game_project.clj:93) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core$map$fn__4785.invoke(core.clj:2644) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.lang.LazySeq.sval(LazySeq.java:40) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.lang.LazySeq.seq(LazySeq.java:49) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.lang.RT.seq(RT.java:521) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core$seq__4357.invokeStatic(core.clj:137) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core.protocols$fn__6738.invokeStatic(protocols.clj:75) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core.protocols$fn__6738.invoke(protocols.clj:75) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6545) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core$group_by.invokeStatic(core.clj:6860) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.game_project_core$category_grouped_settings.invokeStatic(game_project_core.clj:127) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.game_project_core$settings__GT_str.invokeStatic(game_project_core.clj:137) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.game_project$build_game_project.invokeStatic(game_project.clj:95) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.game_project$build_game_project.invoke(game_project.clj:88) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.defold_project$build_target.invokeStatic(defold_project.clj:282) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.defold_project$build$fn__12016.invoke(defold_project.clj:326) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.progress$progress_mapv$fn__8361.invoke(progress.clj:70) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core.protocols$fn__6742.invokeStatic(protocols.clj:75) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core.protocols$fn__6742.invoke(protocols.clj:75) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core.protocols$fn__6684$G__6679__6697.invoke(protocols.clj:13) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core$reduce.invokeStatic(core.clj:6545) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.progress$progress_mapv.invokeStatic(progress.clj:65) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.defold_project$build.invokeStatic(defold_project.clj:321) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.defold_project$build_and_write.invokeStatic(defold_project.clj:346) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at editor.defold_project$build_and_save_project$fn__12696.invoke(defold_project.clj:569) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) ~[defold-62c128b49a72b869380072f0e49bd6ef1b9166a3.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
	... 1 common frames omitted

**Comment by sofiahe** [comment]
Maybe the main.collection was removed due to sync issues, havent seen this again. Close?

**Comment by erikangelin-king** [comment]
Cant reproduce
