### ISSUE TITLE
bob on Windows - Infinity%Exception in thread "main" java.io.IOException: Server returned HTTP response code: 400 for URL

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1758]
```
Infinity%Exception in thread "main" java.io.IOException: Server returned HTTP response code: 400 for URL: https://github.com/defold/extension-fbinstant/archive/master.zip
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(Unknown Source)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
        at com.dynamo.bob.Project.resolveLibUrls(Project.java:1089)
        at com.dynamo.bob.Bob.createProject(Bob.java:269)
        at com.dynamo.bob.Bob.main(Bob.java:310)
Caused by: java.io.IOException: Server returned HTTP response code: 400 for URL: https://github.com/defold/extension-fbinstant/archive/master.zip
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
        at java.base/java.net.HttpURLConnection.getResponseCode(Unknown Source)
        at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(Unknown Source)
        at com.dynamo.bob.Project.resolveLibUrls(Project.java:1069)
        ... 2 more
``

**Comment by subsoap** [comment]
Solution is to add ```--email foo@bar.com --auth 12345 resolve``` to command line options as the libs are hosted on github and it seems to require it.

https://forum.defold.com/t/bob-builder-resolve-libraries-error-solved/5972/8?u=pkeod
