### ISSUE TITLE
bob on Windows - Exception in thread "main" com.dynamo.bob.CompileExceptionError

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#1759]
```
100%Exception in thread "main" com.dynamo.bob.CompileExceptionError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
        at com.dynamo.bob.Project.build(Project.java:347)
        at com.dynamo.bob.Bob.main(Bob.java:339)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
        at com.defold.extender.client.ExtenderClientCache.hashToString(ExtenderClientCache.java:175)
        at com.defold.extender.client.ExtenderClientCache.hash(ExtenderClientCache.java:183)
        at com.defold.extender.client.ExtenderClientCache.getHash(ExtenderClientCache.java:49)
        at com.defold.extender.client.ExtenderClientCache.getHash(ExtenderClientCache.java:63)
        at com.defold.extender.client.ExtenderClientCache.calcKey(ExtenderClientCache.java:98)
        at com.defold.extender.client.ExtenderClient.build(ExtenderClient.java:46)
        at com.dynamo.bob.bundle.BundleHelper.buildEngineRemote(BundleHelper.java:387)
        at com.dynamo.bob.Project.buildEngine(Project.java:659)
        at com.dynamo.bob.Project.doBuild(Project.java:762)
        at com.dynamo.bob.Project.build(Project.java:339)
        ... 1 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.HexBinaryAdapter
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 11 more
Exception in thread "Thread-0" java.lang.RuntimeException: Failed to delete temp directory: C:\Users\Brian\AppData\Local\Temp\8053539896535767771
        at com.dynamo.bob.Bob$1.run(Bob.java:57)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Unable to delete file: C:\Users\Brian\AppData\Local\Temp\8053539896535767771\x86_64-win32\texc_shared.dll
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2279)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
        at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:2270)
        at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1653)
        at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1535)
        at com.dynamo.bob.Bob$1.run(Bob.java:55)
        ... 1 more
```

Putting the temp folders under a Defold folder instead of random numbers only might be a good idea.

**Comment by subsoap** [comment]
https://forum.defold.com/t/bob-java-lang-classnotfoundexception-javax-xml-bind-annotation-adapters-hexbinaryadapter/18060/6
