### ISSUE TITLE
Runner Tutorial HTML5 Build failed

### ISSUE THREAD

**Issue by michaelphipps** [defold/editor2-issues#1796]
### Actual behaviour
Error Message:
java.lang.nullPointerException: Unknown

### Steps to reproduce
Follow Runner Tutorial and select Build HTML5 from menu

<hr/>

<table>
<tr><td>Build time</td><td>2018-04-06T10:48:29.131783</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4be7483ab997ab58c7d8fe930a73774cd81baae5</td></tr>
<tr><td>Defold engine sha</td><td>e3f2a48e6495946eb8aede3c843471bb037976aa</td></tr>
<tr><td>Defold version</td><td>1.2.124</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"5b66923bdab24f8aa6836cead2d10e9f"'>5b66923bdab24f8aa6836cead2d10e9f</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 650/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 NVIDIA 384.111</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.4.0-116-generic</td></tr>
<table>

**Comment by erikangelin-king** [comment]
Hi @michaelphipps! We think the error might have been caused by the content in your project. Would you mind sharing your project? Either by inviting me to the project (erik.angelin@king.com) or just mailing me a zip. Thanks!

**Comment by michaelphipps** [comment]
Hey @erikangelin-king - pretty likely the error is caused by the content of my project.  I've invited you to the project "Run Froggy Run" to take a look.

**Comment by erikangelin-king** [comment]
@michaelphipps I'm having trouble reproducing this, does it happen every time you select Build HTML5?

**Comment by michaelphipps** [comment]
Yes it does.
I've just tried running Defold as root, to see if it was a permission problem.  Same error when I select Build HTML5, but I've got more detail in the console:

2018-04-10 08:29:55.360 ERROR default    editor.error-reporting - {:line 98}
java.lang.NullPointerException: null
	at com.dynamo.bob.pipeline.TextureGenerator.generate(TextureGenerator.java:338)
	at com.dynamo.bob.pipeline.TextureGenerator.generate(TextureGenerator.java:320)
	at com.dynamo.bob.pipeline.TextureBuilder.build(TextureBuilder.java:49)
	at com.dynamo.bob.Project.runTasks(Project.java:919)
	at com.dynamo.bob.Project.doBuild(Project.java:753)
	at com.dynamo.bob.Project.build(Project.java:339)
	at editor.pipeline.bob$run_commands_BANG_.invokeStatic(bob.clj:70)
	at editor.pipeline.bob$bob_build_BANG_$fn__42432.invoke(bob.clj:103)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by michaelphipps** [comment]
Hi @erikangelin-king 

I extracted Image.jar to the same directory.  Here are the results:

michaelphipps@justdoit:~/Downloads/Defold/packages/jre/bin$ ./java -jar Image.jar 
JPG
jpg
bmp
BMP
gif
GIF
WBMP
png
PNG
jpeg
wbmp
JPEG

**Comment by erikangelin-king** [comment]
Thanks @michaelphipps! Our best guess is still something content related. Could you try another experiment? The new jar will try and open whatever image paths we pass on the command line the same way we do it when building. The new command to run would be something like
`find ~/Documents/Run\ Froggy\ Run/ -name "*.png" -print0 | xargs -0 -n 100 ./java -jar Image.jar`
It will print OK/FAIL and the path to the image being tested.
[Image.zip](https://github.com/defold/editor2-issues/files/1898076/Image.zip)

**Comment by michaelphipps** [comment]
@erikangelin-king :)

Righteo... PROBLEM and SOLUTION!  
I had the runner-assets folder containing the assets in the project folder.  I didn't add that folder to the repository because it wasn't important to me - I just figured if it wasn't referenced it would be ignored.

I decided to rename the project and pull a fresh version from the repository.  That didn't contain the additional folder, and when I built the HTML version (after fixing some script errors) I saw the html version of the project!!!

When I added the folders that I had removed from the repository, I got the original error again.

I had no idea that other folders in the project would cause a problem like this.  Guess I know now!

I really appreciate the patience and assistance you've provided.  I'll ask questions in the community first in future to identify if a problem is actually an issue, or just a newbie mistake.

I've included the output of the file below to satisfy your request, but I do consider this issue closed - but I'll leave you with the satisfaction of closing the issue.

RESULTS 

michaelphipps@justdoit:~/Downloads/Defold/packages/jre/bin$ find ~/Run\ Froggy\ Run/ -name "*.png" -print0 | xargs -0 -n 100 ./java -jar Image.jar
OK: /home/michaelphipps/Run Froggy Run/level/images/ground01.png
OK: /home/michaelphipps/Run Froggy Run/level/images/spikes.png
OK: /home/michaelphipps/Run Froggy Run/level/images/rock_planks.png
OK: /home/michaelphipps/Run Froggy Run/level/images/ground02.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/BodyB02.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegLA02.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/ArmL03.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/ThighR.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/ArmR01.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegB04.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/ArmR02.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegR00.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/ArmL02.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/ArmR03.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegB02.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegRA03.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegLA01.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/Head03B.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/Head02.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegB03.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/BodyB01.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegLA03.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/Eye01.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/ThighL.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/Head03.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegL00.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/Head02B.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/BodyA01.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegRA04.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegLA04.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/ArmL01.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegRA01.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/Head01.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegB01.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/BodyA02.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/LegRA02.png
OK: /home/michaelphipps/Run Froggy Run/hero/images/empty.png
FAIL: /home/michaelphipps/Run Froggy Run/runner-assets/__MACOSX/runner-assets/level-images/._bg.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri05.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri19.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri13.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri22.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri11.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri07.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri21.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri14.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri17.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri09.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri06.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri10.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri15.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri12.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri24.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri08.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri04.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri18.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri23.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri16.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/colibri/colibri20.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/items/bubble.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/items/bubble_rocket.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/items/heart.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/items/coin.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/items/bubble_magnet.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_09.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_07.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_05.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_06.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_10.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_12.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_08.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_11.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_00.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/key/key_04.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee08.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Sting04.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot07.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Sting08.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Sting01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee18.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee19.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee06.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee23.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot05.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee24.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee17.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee11.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee14.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee04.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Sting07.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot04.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Sting06.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee13.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot06.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee21.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee15.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot10.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee20.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot08.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Sting09.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Sting03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee16.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Sting05.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee07.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee05.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee10.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee09.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee12.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee22.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Sting02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/extras/bee/Bee_shot09.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/ground01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/spikes.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/bg.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/earthlike_planet.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/heart.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/rock_planks.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/ice_planet.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/gas_planet.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/ground02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/hard.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/ring_planet.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/coin.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/level-images/easy.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/BodyB02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegLA02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/ArmL03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/ThighR.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/ArmR01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegB04.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/ArmR02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegR00.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/ArmL02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/ArmR03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegB02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegRA03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegLA01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/Head03B.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/Head02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegB03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/BodyB01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegLA03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/Eye01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/ThighL.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/Head03.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegL00.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/Head02B.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/BodyA01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegRA04.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegLA04.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/ArmL01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegRA01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/Head01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegB01.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/BodyA02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/LegRA02.png
OK: /home/michaelphipps/Run Froggy Run/runner-assets/runner-assets/hero-images/empty.png
