### ISSUE TITLE
Strange glitch in spine animation on Android

### ISSUE THREAD

**Issue by AGulev** [defold/editor2-issues#1883]
We have strange glitch on one of our animation on android (on mac isn't reproduced):
![2018-05-13_18-41-44](https://user-images.githubusercontent.com/2209596/39968915-4f27e97c-56dd-11e8-97a7-20506457c60c.jpg)

On older defold it works fine. This bug appear in one of last version of engine (I an not sure when exactly)

<hr/>

<table>
<tr><td>Build time</td><td>2018-05-09T12:09:39.008781</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5e191142e56da0ecbc874f924d6a96e32acc02a7</td></tr>
<tr><td>Defold engine sha</td><td>c129eafe38a95a1a69eec93679790cd29ab6c0a6</td></tr>
<tr><td>Defold version</td><td>1.2.127</td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-10.17.5 355.10.05.45f01</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.12.6</td></tr>
<table>

**Comment by mathiaswking** [comment]
HI @AGulev !
Could you perhaps try building with bob? We've recently done some fixes, and we believe this could be one of them.

http://d.defold.com/archive/44a10555cb8edea783af049fef106bcab541cccc/bob/bob.jar

**Comment by AGulev** [comment]
Hi @mathiaswking ,
unfortunately i can't build using bob.jar
When I try I receive an error:
Exception in thread "main" com.dynamo.bob.CompileExceptionError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
	at com.dynamo.bob.Project.build(Project.java:347)
	at com.dynamo.bob.Bob.main(Bob.java:339)
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/adapters/HexBinaryAdapter
	at com.defold.extender.client.ExtenderClientCache.hashToString(ExtenderClientCache.java:175)
	at com.defold.extender.client.ExtenderClientCache.hash(ExtenderClientCache.java:183)
	at com.defold.extender.client.ExtenderClientCache.getHash(ExtenderClientCache.java:49)
	at com.defold.extender.client.ExtenderClientCache.getHash(ExtenderClientCache.java:63)
	at com.defold.extender.client.ExtenderClientCache.calcKey(ExtenderClientCache.java:98)
	at com.defold.extender.client.ExtenderClient.build(ExtenderClient.java:46)
	at com.dynamo.bob.bundle.BundleHelper.buildEngineRemote(BundleHelper.java:399)
	at com.dynamo.bob.Project.buildEngine(Project.java:659)
	at com.dynamo.bob.Project.doBuild(Project.java:762)
	at com.dynamo.bob.Project.build(Project.java:339)
	... 1 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.HexBinaryAdapter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)

**Comment by AGulev** [comment]
@mathiaswking 
I made test project:
[Archive.zip](https://github.com/defold/editor2-issues/files/2000212/Archive.zip)

If I build using editor - the bug is reproduce.
When I try build using with your bob - all fine.

Unfortunately I can't build my main project using bob because of error =(

**Comment by AGulev** [comment]
Nope, in editor everything works perfect.

**Comment by mathiaswking** [comment]
Sure, that would be helpful :)

**Comment by AGulev** [comment]
Done. 
Project "RedHood"
Git branch is "WOW"

**Comment by mathiaswking** [comment]
Hmm, I built it fine with bob.jar here (1.2.127). For android, with texture compression on.

I did however misread your callstack (I thought it was extension related):
Googling the error " java.lang.ClassNotFoundException: javax.xml.bind.annotation.adapters.HexBinaryAdapter" it seems this class is no longer on the class path i Java 1.9 ? Bob it built with Java 1.8. Perhaps that could be a clue?

**Comment by AGulev** [comment]
You are right. Thank you. (I need to add  checker of java version into my bundle.sh)
AGulev-MacBook-Pro:~ agulev$ java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

**Comment by AGulev** [comment]
Is your version of bob.jar stable enough for building the game, how do you think?

**Comment by AGulev** [comment]
@mathiaswking 
I tried to build game with java 1.6 and it's builds without errors, but I have the same problem as before (I thought that build an XML error was the reason) build crashed right after run on device. 
The same code builds using Editor2 works perfectly. (That's why I don't like bob =( )

**Comment by mathiaswking** [comment]
Well, we will test this new bob.jar version with our internal QA on thursday, so it will be more battle tested by then.

**Comment by AGulev** [comment]
Fixed in 1.2.128
