### ISSUE TITLE
Debbuger closed in init fun

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#2016]
### Expected behaviour
debuger worked
### Actual behaviour
debbuger not worked
```
ERROR:SCRIPT: /init_controller_copy.script:17: Debugger connection closed
stack traceback:
	[C]: in function 'error'
	/_defold/debugger/mobdebug.lua:712: in function </_defold/debugger/mobdebug.lua:558>
	/init_controller_copy.script:17: in function </init_controller_copy.script:13>
```

```
2018-07-01 22:33:30.285 128549 [JavaFX Application Thread] ERROR editor.debugging.mobdebug - {:line nil}
clojure.lang.ExceptionInfo: Error decoding serialized data
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at editor.debugging.mobdebug$decode_serialized_data.invokeStatic(mobdebug.clj:102)
	at editor.debugging.mobdebug$stack.invokeStatic(mobdebug.clj:331)
	at editor.debug_view$update_suspension_state_BANG_.invokeStatic(debug_view.clj:346)
	at editor.debug_view$make_debugger_callbacks$fn__45116$fn__45117.invoke(debug_view.clj:355)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Duplicate key: class LogoScene
	at clojure.lang.PersistentArrayMap.createWithCheck(PersistentArrayMap.java:71)
	at clojure.lang.RT.map(RT.java:1551)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:631)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader.read(EdnReader.java:108)
	at clojure.lang.EdnReader.readString(EdnReader.java:64)
	at clojure.edn$read_string.invokeStatic(edn.clj:46)
	... 12 common frames omitted
2018-07-01 22:34:11.447 169711 [JavaFX Application Thread] ERROR editor.debugging.mobdebug - {:line nil}
clojure.lang.ExceptionInfo: Error decoding serialized data
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at editor.debugging.mobdebug$decode_serialized_data.invokeStatic(mobdebug.clj:102)
	at editor.debugging.mobdebug$stack.invokeStatic(mobdebug.clj:331)
	at editor.debug_view$update_suspension_state_BANG_.invokeStatic(debug_view.clj:346)
	at editor.debug_view$make_debugger_callbacks$fn__45116$fn__45117.invoke(debug_view.clj:355)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Duplicate key: class LogoScene
	at clojure.lang.PersistentArrayMap.createWithCheck(PersistentArrayMap.java:71)
	at clojure.lang.RT.map(RT.java:1551)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:631)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.readDelimitedList(EdnReader.java:685)
	at clojure.lang.EdnReader$MapReader.invoke(EdnReader.java:628)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader$TaggedReader.readTagged(EdnReader.java:718)
	at clojure.lang.EdnReader$TaggedReader.invoke(EdnReader.java:711)
	at clojure.lang.EdnReader$DispatchReader.invoke(EdnReader.java:497)
	at clojure.lang.EdnReader.read(EdnReader.java:142)
	at clojure.lang.EdnReader.read(EdnReader.java:108)
	at clojure.lang.EdnReader.readString(EdnReader.java:64)
	at clojure.edn$read_string.invokeStatic(edn.clj:46)
	... 12 common frames omitted
```
### Steps to reproduce
1)Not sure. I get error when add breakpoint in init. I can add someone to project, if it will help
2)Breakpoint in update worked
<hr/>

<table>
<tr><td>Build time</td><td>2018-06-25T12:13:01.378662</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>3af7e148260175bcaedb62b7e9ae442d08dfac4d</td></tr>
<tr><td>Defold engine sha</td><td>091e7e02ce492d3c4e493324b9db57d40df69e95</td></tr>
<tr><td>Defold version</td><td>1.2.131</td></tr>
<tr><td>GPU</td><td>AMD Radeon HD 7800 Series</td></tr>
<tr><td>GPU Driver</td><td>4.5.13506 Compatibility Profile Context 23.20.15002.11</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by d954mas** [comment]
Add to project. You need init copy collection. Breakpoint inside init function

**Comment by d954mas** [comment]
Any news. It is hard to work without debugger. It don't work in any line.

**Comment by erikangelin-king** [comment]
Hi @d954mas! We're just back from vacations. Right now we have some more pressing issues, but I hope we can get to this soon-ish.

**Comment by d954mas** [comment]
Any news. Have very similar  issue yesterday. Now can't find logs and repeat.

**Comment by erikangelin-king** [comment]
Fixed!
