### ISSUE TITLE
Cannot start debuging on Ubuntu

### ISSUE THREAD

**Issue by Atanvadro** [defold/editor2-issues#2137]
### Expected behaviour
Debugging process is started

### Actual behaviour
Error message occurs: clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172

### Steps to reproduce
Install editor, create new project and press F5

<hr/>

<table>
<tr><td>Build time</td><td>2018-08-15T15:08:40.873906</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>647b78d3829e45c0a9ab3b643d426a12feaba2da</td></tr>
<tr><td>Defold engine sha</td><td>b2ef3a19802728e76adf84d51d02e11d636791a3</td></tr>
<tr><td>Defold version</td><td>1.2.134</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"3a9d7c68206b4e93866a49f05a875e0e"'>3a9d7c68206b4e93866a49f05a875e0e</a></td></tr>
<tr><td>GPU</td><td>Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) </td></tr>
<tr><td>GPU Driver</td><td>3.0 Mesa 18.0.5</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Linux</td></tr>
<tr><td>OS version</td><td>4.15.0-32-generic</td></tr>
<table>

**Comment by Atanvadro** [comment]
Console output is this:
2018-08-19 12:58:46.130 ERROR default    editor.error-reporting - {:line 98}
clojure.lang.ExceptionInfo: Failed to connect to debugger on localhost:8172
	at clojure.core$ex_info.invokeStatic(core.clj:4617)
	at editor.debugging.mobdebug$connect_BANG_$fn__38218.invoke(mobdebug.clj:174)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by Atanvadro** [comment]
Issue solved by installing libopenal1:
sudo apt-get install libopenal1
