### ISSUE TITLE
Update problem (Windows) 

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#2200]
https://forum.defold.com/t/is-there-an-update-problem-windows/30024

> Hi @Erik_Angelin,
No I’m not getting the “Update Available” message. I did, ever since starting using defold over 6 months ago, but I noticed that since version 1.2.136 2018-09-11 it stopped appearing (I think it was this version but could be a few days off).
I manually updated to 1.2.136 2018-09-19 Friday but I still don’t get the update available message on this either.
BR

**Comment by subsoap** [comment]
I'm still getting regular updates on Windows 10.

**Comment by approboGames** [comment]
This problem is still occuring for me. I got an "UPDATE AVAILABLE" prompt in the bottom corner shortly after 1.2.141. I did not update and still on 1.2.140 but the prompt is no longer showing.

After further investigation there may be more info in the log refering to this (based on timestamp).

`2018-11-14 21:38:57.716 7278  <-- Previous log entry timestamp`

`2018-11-14 21:39:09.473 19035 [JavaFX Application Thread] WARN  java.util.prefs - Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
2018-11-14 21:39:09.486 19048 [JavaFX Application Thread] INFO  editor.updater - {:line 87, :message "automatic updates enabled (channel='editor-alpha')"}
2018-11-14 21:39:10.527 20089 [Timer-0] INFO  editor.updater - {:line 43, :message "checking for updates"}
2018-11-14 21:39:10.614 20176 [Timer-0] DEBUG com.defold.editor.Updater - checking for update url='https://d.defold.com/editor2/channels/editor-alpha/update.json'
2018-11-14 21:39:12.013 21575 [Timer-0] INFO  com.defold.editor.Updater - new version found dfbd3470660278721c7a0eea27f9e57d53590564
2018-11-14 21:39:12.014 21576 [Timer-0] INFO  com.defold.editor.Updater - downloading defold-dfbd3470660278721c7a0eea27f9e57d53590564.jar -> C:\Users\%USERNAME%\AppData\Local\Temp\1877725520535020641\7672463945490467906.tmp
2018-11-14 21:39:12.133 21695 [JavaFX Application Thread] WARN  editor.login - {:line 22}
com.sun.jersey.api.client.UniformInterfaceException: GET https://cr.defold.com/users/%EMAIL% returned a response status of 403 Forbidden
	at com.sun.jersey.api.client.WebResource.handle(WebResource.java:688)
	at com.sun.jersey.api.client.WebResource.access$200(WebResource.java:74)
	at com.sun.jersey.api.client.WebResource$Builder.get(WebResource.java:509)
	at editor.client$cr_get.invokeStatic(client.clj:54)
	at editor.client$user_info.invokeStatic(client.clj:87)
	at editor.login$logged_in_QMARK_.invokeStatic(login.clj:17)
	at editor.welcome$make_dashboard_client.invokeStatic(welcome.clj:243)
	at editor.welcome$show_welcome_dialog_BANG_.invokeStatic(welcome.clj:737)
	at editor.welcome$show_welcome_dialog_BANG_.invoke(welcome.clj:733)
	at editor.welcome$show_welcome_dialog_BANG_.invokeStatic(welcome.clj:735)
	at editor.boot$select_project_from_welcome$fn__147736.invoke(boot.clj:68)
	at clojure.lang.AFn.run(AFn.java:22)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)`

`2018-11-14 21:39:38.806 48368  <-- Next log entry timestamp`

**Comment by vlaaad** [comment]
We changed our update system and reportedly this is no longer an issue. Feel free to reopen if it still happens to you after newer updates.
