### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException: String index out of range: -6 (DEF-3530, DEFEDIT-1462)

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2206]
Editing GUI
Changed color and Alpha
<hr/>

<table>
<tr><td>Build time</td><td>2018-09-25T12:46:50.778120</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>fd7af61974003c7b8528f2aa28306636a7241354</td></tr>
<tr><td>Defold engine sha</td><td>936eee90249fcf505f8dbe5b215db5d165221cca</td></tr>
<tr><td>Defold version</td><td>1.2.137</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ffb77c53caf64019a42b8171dbd2e20d"'>ffb77c53caf64019a42b8171dbd2e20d</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by Jerakin** [comment]
Also editing files outside of the editor but the error came up as I tried to build after changing the gui

**Comment by Jerakin** [comment]
Got a lot of this
```
WARNING:DLIB: Unable to remove /Users/jerakin/Library/Application Support/defold/cache/00/00000000000000
WARNING:DLIB: Unable to remove /Users/jerakin/Library/Application Support/defold/cache/65/6c636974726170
WARNING:DLIB: Unable to remove /Users/jerakin/Library/Application Support/defold/cache/00/00000000000000
WARNING:DLIB: Unable to remove /Users/jerakin/Library/Application Support/defold/cache/00/0576b06475c64e
WARNING:DLIB: Unable to remove /Users/jerakin/Library/Application Support/defold/cache/00/00000000000000
WARNING:DLIB: Unable to remove /Users/jerakin/Library/Application Support/defold/cache/65/6c636974726170
WARNING:DLIB: Unable to remove /Users/jerakin/Library/Application Support/defold/cache/00/00000000000000
```

The app/game crashes and I need to force quit it to be able to rebuild it. If I don't this happens making me unable to rebuild
![screen shot 2018-09-26 at 13 54 36](https://user-images.githubusercontent.com/5273682/46078194-bc66b100-c193-11e8-8974-6247af5d99db.png)

**Comment by erikangelin-king** [comment]
Hi @Jerakin! @tarrekkarray got something similar here: #2203 It seems the engine resource cache has become corrupt for some reason. In his case a workaround was to simply delete the folder. Could you please make a copy first so we can try and repro the issue properly?

**Comment by Jerakin** [comment]
Clearing the cache solved the issue

**Comment by mathiaswking** [comment]
Aanother relaated callstack:

2018-10-02 09:24:54.237 25594 [Thread-21] ERROR editor.error-reporting - {:line 98}
java.lang.NullPointerException: null
	at java.net.URI$Parser.parse(URI.java:3042)
	at java.net.URI.<init>(URI.java:588)
	at editor.hot_reload$v_e_handler$fn__37715.invoke(hot_reload.clj:57)
	at clojure.core$keep$fn__7061.invoke(core.clj:7051)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.LazySeq.first(LazySeq.java:71)
	at clojure.lang.RT.first(RT.java:667)
	at clojure.core$first__4339.invokeStatic(core.clj:55)
	at clojure.string$join.invokeStatic(string.clj:180)
	at editor.hot_reload$v_e_handler.invokeStatic(hot_reload.clj:51)
	at editor.hot_reload$verify_etags_handler.invokeStatic(hot_reload.clj:69)
	at editor.hot_reload$verify_etags_handler.invoke(hot_reload.clj:69)
	at clojure.core$partial$fn__4761.invoke(core.clj:2522)
	at util.http_server$setup_server_BANG_$reify__12704.handle(http_server.clj:49)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:745)

	
Not a fix for the root cause, but I think that hot_reload.clj should handle bad content more graaaacefully. Currently the engine then hangs on waiting for a response. I think sending some response at least should make the engine not hang.

**Comment by mathiaswking** [comment]
The engine part of this is done. Now the editor also needs to more gracefully handle bad requests.

**Comment by erikangelin-king** [comment]
Editor now more resilient to bad requests.
