### ISSUE TITLE
Bob gives me (Access is denied) when resolving

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2323]
Command
`"java -jar project.bob --email 'asd' --auth 'asd' resolve"`
gives me 

```
Exception in thread "main" com.dynamo.bob.CompileExceptionError: D:\Repo\<game>\build\default\state (Access is denied)
        at com.dynamo.bob.Project.build(Project.java:353)
        at com.dynamo.bob.Bob.main(Bob.java:430)
Caused by: java.io.FileNotFoundException: D:\Repo\<game>\build\default\state (Access is denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.dynamo.bob.fs.DefaultResource.getContent(DefaultResource.java:27)
        at com.dynamo.bob.State.load(State.java:49)
        at com.dynamo.bob.Project.doBuild(Project.java:727)
        at com.dynamo.bob.Project.build(Project.java:345)
        ... 1 more
```

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-19T15:12:31.026375</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4fd5fc8a52c9d55a19871e3e2c16ff5c14898c2a</td></tr>
<tr><td>Defold engine sha</td><td>6230c40dfa051a311aa4005c19097574e062374d</td></tr>
<tr><td>Defold version</td><td>1.2.142</td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by mathiaswking** [comment]
What version is project.bob?

**Comment by Jerakin** [comment]
Newest - 6230c40dfa051a311aa4005c19097574e062374d

**Comment by Jerakin** [comment]
I really want bob to work so I tried a few other versions :( 
# 1.2.143 -> 1.2.139
```
Exception in thread "main" com.dynamo.bob.CompileExceptionError: D:\Repo\<game>\build\default\state (Access is denied)
        at com.dynamo.bob.Project.build(Project.java:353)
        at com.dynamo.bob.Bob.main(Bob.java:396)
Caused by: java.io.FileNotFoundException: D:\Repo\<game>\build\default\state (Access is denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.dynamo.bob.fs.DefaultResource.getContent(DefaultResource.java:27)
        at com.dynamo.bob.State.load(State.java:49)
        at com.dynamo.bob.Project.doBuild(Project.java:721)
        at com.dynamo.bob.Project.build(Project.java:345)
        ... 1 more
```
# 1.2.130
```
Exception in thread "main" com.dynamo.bob.CompileExceptionError: D:\Repo\<game>\build\default\state (Access is denied)
        at com.dynamo.bob.Project.build(Project.java:347)
        at com.dynamo.bob.Bob.main(Bob.java:339)
Caused by: java.io.FileNotFoundException: D:\Repo\<game>\build\default\state (Access is denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.dynamo.bob.fs.DefaultResource.getContent(DefaultResource.java:27)
        at com.dynamo.bob.State.load(State.java:49)
        at com.dynamo.bob.Project.doBuild(Project.java:725)
        at com.dynamo.bob.Project.build(Project.java:339)
        ... 1 more
```
# 1.2.120
```
Exception in thread "main" com.dynamo.bob.CompileExceptionError: D:\Repo\<game>\build\default\state (Access is denied)
        at com.dynamo.bob.Project.build(Project.java:347)
        at com.dynamo.bob.Bob.main(Bob.java:331)
Caused by: java.io.FileNotFoundException: D:\Repo\<game>\build\default\state (Access is denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.dynamo.bob.fs.DefaultResource.getContent(DefaultResource.java:27)
        at com.dynamo.bob.State.load(State.java:49)
        at com.dynamo.bob.Project.doBuild(Project.java:714)
        at com.dynamo.bob.Project.build(Project.java:339)
        ... 1 more
```
# 1.2.100
```
Exception in thread "main" com.dynamo.bob.CompileExceptionError: D:\Repo\<game>\build\default\state (Access is denied)
        at com.dynamo.bob.Project.build(Project.java:337)
        at com.dynamo.bob.Bob.main(Bob.java:294)
Caused by: java.io.FileNotFoundException: D:\Repo\<game>\build\default\state (Access is denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.dynamo.bob.fs.DefaultResource.getContent(DefaultResource.java:27)
        at com.dynamo.bob.State.load(State.java:49)
        at com.dynamo.bob.Project.doBuild(Project.java:545)
        at com.dynamo.bob.Project.build(Project.java:329)
```
# 1.2.80
```
Exception in thread "main" com.dynamo.bob.CompileExceptionError: D:\Repo\<game>\build\default\state (Access is denied)
        at com.dynamo.bob.Project.build(Project.java:261)
        at com.dynamo.bob.Bob.main(Bob.java:270)
Caused by: java.io.FileNotFoundException: D:\Repo\<game>\build\default\state (Access is denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.dynamo.bob.fs.DefaultResource.getContent(DefaultResource.java:27)
        at com.dynamo.bob.State.load(State.java:49)
        at com.dynamo.bob.Project.doBuild(Project.java:418)
        at com.dynamo.bob.Project.build(Project.java:256)
        ... 1 more
```
___

Other things I tried
- Elevated PowerShell
- PowerShell 
- Elevated cmd
- cmd

Also tried moving the project over to `C:`

**Comment by Jerakin** [comment]
Something is wrong with my project. Here are some stuff that I have checked directly and indirectly:
* I can't even bundle the app from within Defold.
* I could download and bundle "Mobile Game" within Defold
* Build and Rebuild both works and I get the project running locally. 
* Explicitly starting Defold Elevated does nothing (should start as it anyway)
* I verified that the files are *not* read only.
* I can fetch libraries within Defold but not resolve with Bob (because then bob looks in ./build/default/*)
* Removing the build folder before resolve with Bob makes the resolve command *not* give error
* Removing the dependencies does nothing
* Copying in the dependencies locally does nothing
* Removing the files in the folder still gives the error on the folder
* Removing the folder removes the error (duh)
* The error stops bob from cleaning the build folder
    * Deleting just the folder that gives the problems makes bob able to clean the build folder

**Comment by Jerakin** [comment]
* I have two cases
    * `/states` Moving folder and re-linking all lua files solves this issue
    * `/assets/defintions` Trying to have a "definition" file but as soon as I add a **empty** folder and hook it up in the game.project the game doesn't bundle any more, tried with many different locations.

**Comment by Jerakin** [comment]
Adding a `/assets/defintions` in "Mobile Game" example breaks it too
```
Exception in thread "main" com.dynamo.bob.CompileExceptionError: D:\Repo\Mobile game\assets\definitions (Access is denied)
        at com.dynamo.bob.Project.build(Project.java:353)
        at com.dynamo.bob.Bob.main(Bob.java:396)
Caused by: java.io.FileNotFoundException: D:\Repo\Mobile game\assets\definitions (Access is denied)
        at java.io.FileInputStream.open(Native Method)
        at java.io.FileInputStream.<init>(Unknown Source)
        at com.dynamo.bob.fs.DefaultResource.getContent(DefaultResource.java:27)
        at com.dynamo.bob.fs.DefaultFileSystem.calcSha1(DefaultFileSystem.java:44)
        at com.dynamo.bob.fs.DefaultFileSystem.sha1(DefaultFileSystem.java:67)
        at com.dynamo.bob.fs.DefaultResource.sha1(DefaultResource.java:75)
        at com.dynamo.bob.Task.calculateSignature(Task.java:120)
        at com.dynamo.bob.Project.runTasks(Project.java:866)
        at com.dynamo.bob.Project.doBuild(Project.java:749)
        at com.dynamo.bob.Project.build(Project.java:345)
        ... 1 more
```

**Comment by Jerakin** [comment]
@mathiaswking Do you guys have an update on this? Having bob not working at all is quite bad.

**Comment by Jerakin** [comment]
I would almost argue that it is a bit of an blocker 🙃 Would be interesting to hear if this at least have happened to anyone else

**Comment by Jerakin** [comment]
This seems to be an issue with my machine, I tried with a different machine and it worked (almost) as expected (got an errror about a temp folder).
