### ISSUE TITLE
Project can't be opened

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#2346]
### Steps to reproduce
1)Try to open project
2)It show loading ui
3)loading ui closed and editor not running. No errors for user

2018-12-02 23:21:22.215 13028 [JavaFX Application Thread] WARN  java.util.prefs - Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
2018-12-02 23:21:22.240 13053 [JavaFX Application Thread] INFO  editor.updater - {:line 87, :message "automatic updates enabled (channel='editor-alpha')"}
2018-12-02 23:21:23.247 14060 [Timer-0] INFO  editor.updater - {:line 43, :message "checking for updates"}
2018-12-02 23:21:23.252 14065 [Timer-0] DEBUG com.defold.editor.Updater - checking for update url='https://d.defold.com/editor2/channels/editor-alpha/update.json'
2018-12-02 23:21:25.636 16449 [Timer-0] INFO  editor.updater - {:line 52, :message "no update found"}
2018-12-02 23:21:37.884 28697 [clojure-agent-send-off-pool-1] ERROR editor.ui - {:line 1738}
java.lang.ClassCastException: internal.graph.error_values.ErrorValue cannot be cast to clojure.lang.IFn
	at editor.collection$fn__121016$ReferencedGOInstanceNode$property$path$setter__121031$fn__121037$id_mapping__121038.invoke(collection.clj:243)
	at editor.collection$fn__121016$ReferencedGOInstanceNode$property$path$setter__121031$fn__121037$iter__121085__121091$fn__121092$iter__121087__121094$fn__121095.invoke(collection.clj:243)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at editor.collection$fn__121016$ReferencedGOInstanceNode$property$path$setter__121031$fn__121037$iter__121085__121091$fn__121092.invoke(collection.clj:243)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$concat$cat__4448$fn__4449.invoke(core.clj:715)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:56)
	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
	at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
	at clojure.lang.RT.next(RT.java:688)
	at clojure.core$next__4341.invokeStatic(core.clj:64)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:651)
	at internal.transaction$apply_tx.invoke(transaction.clj:644)
	at internal.transaction$fn__5914.invokeStatic(transaction.clj:347)
	at internal.transaction$fn__5914.invoke(transaction.clj:327)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at internal.transaction$apply_tx$fn__6042.invoke(transaction.clj:654)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:654)
	at internal.transaction$apply_tx.invoke(transaction.clj:644)
	at internal.transaction$invoke_setter$fn__5966.invoke(transaction.clj:477)
	at internal.transaction$invoke_setter.invokeStatic(transaction.clj:477)
	at internal.transaction$apply_defaults.invokeStatic(transaction.clj:485)
	at internal.transaction$ctx_add_node.invokeStatic(transaction.clj:493)
	at internal.transaction$fn__5978.invokeStatic(transaction.clj:502)
	at internal.transaction$fn__5978.invoke(transaction.clj:501)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at internal.transaction$apply_tx$fn__6042.invoke(transaction.clj:654)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:654)
	at internal.transaction$apply_tx.invoke(transaction.clj:644)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:651)
	at internal.transaction$apply_tx.invoke(transaction.clj:644)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:651)
	at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:721)
	at dynamo.graph$transact.invokeStatic(graph.clj:133)
	at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:161)
	at editor.defold_project$load_project$fn__17766.invoke(defold_project.clj:208)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at editor.defold_project$load_project.invokeStatic(defold_project.clj:208)
	at editor.defold_project$open_project_BANG_.invokeStatic(defold_project.clj:755)
	at editor.boot_open_project$open_project.invokeStatic(boot_open_project.clj:327)
	at editor.boot_open_project$open_project.invoke(boot_open_project.clj:325)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at editor.boot$open_project_with_progress_dialog$fn__147561.invoke(boot.clj:53)
	at editor.ui$modal_progress$fn__11944$fn__11947$fn__11948.invoke(ui.clj:1736)
	at editor.ui$modal_progress$fn__11944$fn__11947.invoke(ui.clj:1735)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2018-12-02 23:21:37.892 28705 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 98}
java.lang.ClassCastException: internal.graph.error_values.ErrorValue cannot be cast to clojure.lang.IFn
	at editor.collection$fn__121016$ReferencedGOInstanceNode$property$path$setter__121031$fn__121037$id_mapping__121038.invoke(collection.clj:243)
	at editor.collection$fn__121016$ReferencedGOInstanceNode$property$path$setter__121031$fn__121037$iter__121085__121091$fn__121092$iter__121087__121094$fn__121095.invoke(collection.clj:243)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at editor.collection$fn__121016$ReferencedGOInstanceNode$property$path$setter__121031$fn__121037$iter__121085__121091$fn__121092.invoke(collection.clj:243)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.RT.seq(RT.java:521)
	at clojure.core$seq__4357.invokeStatic(core.clj:137)
	at clojure.core$concat$cat__4448$fn__4449.invoke(core.clj:715)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:56)
	at clojure.lang.ChunkedCons.chunkedNext(ChunkedCons.java:59)
	at clojure.lang.ChunkedCons.next(ChunkedCons.java:43)
	at clojure.lang.RT.next(RT.java:688)
	at clojure.core$next__4341.invokeStatic(core.clj:64)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:651)
	at internal.transaction$apply_tx.invoke(transaction.clj:644)
	at internal.transaction$fn__5914.invokeStatic(transaction.clj:347)
	at internal.transaction$fn__5914.invoke(transaction.clj:327)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at internal.transaction$apply_tx$fn__6042.invoke(transaction.clj:654)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:654)
	at internal.transaction$apply_tx.invoke(transaction.clj:644)
	at internal.transaction$invoke_setter$fn__5966.invoke(transaction.clj:477)
	at internal.transaction$invoke_setter.invokeStatic(transaction.clj:477)
	at internal.transaction$apply_defaults.invokeStatic(transaction.clj:485)
	at internal.transaction$ctx_add_node.invokeStatic(transaction.clj:493)
	at internal.transaction$fn__5978.invokeStatic(transaction.clj:502)
	at internal.transaction$fn__5978.invoke(transaction.clj:501)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at internal.transaction$apply_tx$fn__6042.invoke(transaction.clj:654)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:654)
	at internal.transaction$apply_tx.invoke(transaction.clj:644)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:651)
	at internal.transaction$apply_tx.invoke(transaction.clj:644)
	at internal.transaction$apply_tx.invokeStatic(transaction.clj:651)
	at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:721)
	at dynamo.graph$transact.invokeStatic(graph.clj:133)
	at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:161)
	at editor.defold_project$load_project$fn__17766.invoke(defold_project.clj:208)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at editor.defold_project$load_project.invokeStatic(defold_project.clj:208)
	at editor.defold_project$open_project_BANG_.invokeStatic(defold_project.clj:755)
	at editor.boot_open_project$open_project.invokeStatic(boot_open_project.clj:327)
	at editor.boot_open_project$open_project.invoke(boot_open_project.clj:325)
	at clojure.lang.AFn.applyToHelper(AFn.java:171)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at editor.boot$open_project_with_progress_dialog$fn__147561.invoke(boot.clj:53)
	at editor.ui$modal_progress$fn__11944$fn__11947$fn__11948.invoke(ui.clj:1736)
	at editor.ui$modal_progress$fn__11944$fn__11947.invoke(ui.clj:1735)
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[My Project.zip](https://github.com/defold/editor2-issues/files/2637351/My.Project.zip)

<hr/>

<table>
<tr><td>Build time</td><td>2018-11-28T10:40:18.269998</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>496c3b0afba64917c0993ed33be59c081d2ad99a</td></tr>
<tr><td>Defold engine sha</td><td>6230c40dfa051a311aa4005c19097574e062374d</td></tr>
<tr><td>Defold version</td><td>1.2.142</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4600</td></tr>
<tr><td>GPU Driver</td><td>4.2.0 - Build 10.18.10.4425</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by erikangelin-king** [comment]
@d954mas /simple_lights/simple_lights/simplelights.collection refers to the missing file /orthographic/camera.go, and we apparently do not handle that very gracefully when loading. Working on a fix. As a workaround, you could probably move the simple_lights directory out of the project directory, open the project, add orthographic as a dependency, fetch libraries, verify that /orthographic/camera.go shows up in the asset browser, close the editor, move simple_lights back to the project directory and restart.
