### ISSUE TITLE
java.security.PrivilegedActionException when bundling

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2531]
java.security.PrivilegedActionException: Unknown
java.net.SocketException: Connection reset

Tried bundling Windows, Mac, Android, HTML5

Tried to connect to different WiFis and also cable.

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-21T17:01:42.269967</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>f475fdb0d7584c8615390a32c72d54ec20487cf8</td></tr>
<tr><td>Defold engine sha</td><td>34bb9603dfcb145c74fbb4f36f4146acea4c4252</td></tr>
<tr><td>Defold version</td><td>1.2.149</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"2e65c231f58f4adcb2f095bb39fc5914"'>2e65c231f58f4adcb2f095bb39fc5914</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by vlaaad** [comment]
Are you bundling from the editor? Does it happen when you bundle using bob?

**Comment by Jerakin** [comment]
Tried to resolve with bob and instantly go this
```
Exception in thread "main" java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1587)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.dynamo.bob.Project.resolveLibUrls(Project.java:1094)
	at com.dynamo.bob.Bob.createProject(Bob.java:339)
	at com.dynamo.bob.Bob.main(Bob.java:392)
```

**Comment by vlaaad** [comment]
What is your `java -version`?

**Comment by vlaaad** [comment]
in the command line when bundling with bob

**Comment by Jerakin** [comment]
```

java version "1.8.0_171"
Java(TM) SE Runtime Environment (build 1.8.0_171-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.171-b11, mixed mode)

```

**Comment by Jerakin** [comment]
The error was because of a temporary problem resolving a internal url. The fix would be to display a more informative message to the user than a crash report :)
