### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2551]
I assume it is because the editor was forced resized after plugging in the laptop into my two external monitors.

![Screen Shot 2019-04-11 at 09 48 05](https://user-images.githubusercontent.com/5273682/55939885-37c71600-5c3f-11e9-9b15-f80a968b47e2.png)

<hr/>

<table>
<tr><td>Build time</td><td>2019-03-28T16:26:18.036287</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>32bed942610e57c62b906627bdec4845f354392f</td></tr>
<tr><td>Defold engine sha</td><td>34bb9603dfcb145c74fbb4f36f4146acea4c4252</td></tr>
<tr><td>Defold version</td><td>1.2.149</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"dd47d79a834948f286c9706388890439"'>dd47d79a834948f286c9706388890439</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by matgis-king** [comment]
Callstack is entirely within JavaFX:
```
javafx.geometry.Rectangle2D.<init>.class java.lang.IllegalArgumentException: Both width and height must be >= 0
    at javafx.geometry.Rectangle2D.<init>(Rectangle2D.java:110)
    at javafx.stage.Screen.nativeToScreen(Screen.java:153)
    at javafx.stage.Screen.updateConfiguration(Screen.java:107)
    at javafx.stage.Screen.lambda$static$0(Screen.java:74)
    at com.sun.javafx.tk.quantum.QuantumToolkit.notifyScreenListener(QuantumToolkit.java:744)
    at com.sun.javafx.tk.quantum.QuantumToolkit$4.handleSettingsChanged(QuantumToolkit.java:729)
    at com.sun.glass.ui.Screen.notifySettingsChanged(Screen.java:384)
```

**Comment by matgis-king** [comment]
Looks like this: https://bugs.openjdk.java.net/browse/JDK-8198679
