### ISSUE TITLE
Pasting in a node hierarchy from a second instance of defold (running a different project)

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2565]
<hr/>

<table>
<tr><td>Build time</td><td>2019-04-17T18:28:30.387616</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>759189e7da3bb46f6a2655c10a2230e8ab48d4c4</td></tr>
<tr><td>Defold engine sha</td><td>e05232d70b8a6d8c69fcfe968f01b876090ffa06</td></tr>
<tr><td>Defold version</td><td>1.2.151</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"3cd54a2135234cf5a8170ce882c94328"'>3cd54a2135234cf5a8170ce882c94328</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
```
editor.handler$invoke_fnk.invokeStatic.class clojure.lang.ExceptionInfo: handler ':paste' in context ':workbench' failed at ':run' with message 'Setter of node 72057594037928614 (editor.gui/TemplateNode) :template could not be called'
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:71)
    at editor.handler$run.invokeStatic(handler.clj:97)
    at editor.ui$execute_command.invokeStatic(ui.clj:1038)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1059)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1145)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$1(ControlAcceleratorSupport.java:165)
    at com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:382)
    at com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:162)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$KeyHandler.process(Scene.java:4070)
    at javafx.scene.Scene.processKeyEvent(Scene.java:2121)
    at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2597)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
    at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
    at com.sun.glass.ui.View.notifyKey(View.java:971)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
internal.transaction$call_setter_fn.invokeStatic.class java.lang.Exception: Setter of node 72057594037928614 (editor.gui/TemplateNode) :template could not be called
    at internal.transaction$call_setter_fn.invokeStatic(transaction.clj:432)
    at internal.transaction$invoke_setter$fn.invoke(transaction.clj:460)
    at internal.transaction$invoke_setter.invokeStatic(transaction.clj:460)
    at internal.transaction$apply_defaults.invokeStatic(transaction.clj:468)
    at internal.transaction$ctx_add_node.invokeStatic(transaction.clj:476)
    at internal.transaction$fn.invokeStatic(transaction.clj:485)
    at internal.transaction$fn.invoke(transaction.clj:484)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn.invoke(transaction.clj:637)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:637)
    at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:704)
    at dynamo.graph$transact.invokeStatic(graph.clj:133)
    at editor.outline$do_paste_BANG_.invokeStatic(outline.clj:212)
    at editor.outline$paste_BANG_.invokeStatic(outline.clj:239)
    at editor.outline_view$fn$fnk81549_positional__81554.invoke(outline_view.clj:332)
    at editor.outline_view$fn$fnk81549__81565$fn.invoke(outline_view.clj:319)
    at editor.outline_view$fn$fnk81549__81565.invoke(outline_view.clj:319)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:65)
    at editor.handler$run.invokeStatic(handler.clj:97)
    at editor.ui$execute_command.invokeStatic(ui.clj:1038)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1059)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1145)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$1(ControlAcceleratorSupport.java:165)
    at com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:382)
    at com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:162)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$KeyHandler.process(Scene.java:4070)
    at javafx.scene.Scene.processKeyEvent(Scene.java:2121)
    at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2597)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
    at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
    at com.sun.glass.ui.View.notifyKey(View.java:971)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
clojure.core$_cache_protocol_fn.invokeStatic.class java.lang.IllegalArgumentException: No implementation of method: :produce-value of protocol: #'internal.graph.types/Evaluation found for class: nil
    at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:583)
    at internal.graph.types$fn$G__3161__3175.invoke(types.clj:14)
    at internal.node$node_value.invokeStatic(node.clj:392)
    at internal.system$node_value.invokeStatic(system.clj:341)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:776)
    at dynamo.graph$node_value.invokeStatic(graph.clj:779)
    at editor.gui$TemplateNode$property$template$setter.invokeStatic(gui.clj:1268)
    at editor.gui$TemplateNode$property$template$setter.invoke(gui.clj:1256)
    at internal.transaction$call_setter_fn.invokeStatic(transaction.clj:423)
    at internal.transaction$invoke_setter$fn.invoke(transaction.clj:460)
    at internal.transaction$invoke_setter.invokeStatic(transaction.clj:460)
    at internal.transaction$apply_defaults.invokeStatic(transaction.clj:468)
    at internal.transaction$ctx_add_node.invokeStatic(transaction.clj:476)
    at internal.transaction$fn.invokeStatic(transaction.clj:485)
    at internal.transaction$fn.invoke(transaction.clj:484)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn.invoke(transaction.clj:637)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:637)
    at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:704)
    at dynamo.graph$transact.invokeStatic(graph.clj:133)
    at editor.outline$do_paste_BANG_.invokeStatic(outline.clj:212)
    at editor.outline$paste_BANG_.invokeStatic(outline.clj:239)
    at editor.outline_view$fn$fnk81549_positional__81554.invoke(outline_view.clj:332)
    at editor.outline_view$fn$fnk81549__81565$fn.invoke(outline_view.clj:319)
    at editor.outline_view$fn$fnk81549__81565.invoke(outline_view.clj:319)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:65)
    at editor.handler$run.invokeStatic(handler.clj:97)
    at editor.ui$execute_command.invokeStatic(ui.clj:1038)
    at editor.ui$invoke_handler.invokeStatic(ui.clj:1059)
    at editor.ui$make_menu_command$reify.handle(ui.clj:1145)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.control.MenuItem.fire(MenuItem.java:459)
    at com.sun.javafx.scene.control.ControlAcceleratorSupport.lambda$doAcceleratorInstall$1(ControlAcceleratorSupport.java:165)
    at com.sun.javafx.scene.KeyboardShortcutsHandler.processAccelerators(KeyboardShortcutsHandler.java:382)
    at com.sun.javafx.scene.KeyboardShortcutsHandler.dispatchBubblingEvent(KeyboardShortcutsHandler.java:162)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$KeyHandler.process(Scene.java:4070)
    at javafx.scene.Scene.processKeyEvent(Scene.java:2121)
    at javafx.scene.Scene$ScenePeerListener.keyEvent(Scene.java:2597)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:217)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$KeyEventNotification.run(GlassViewEventHandler.java:149)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleKeyEvent$1(GlassViewEventHandler.java:248)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleKeyEvent(GlassViewEventHandler.java:247)
    at com.sun.glass.ui.View.handleKeyEvent(View.java:547)
    at com.sun.glass.ui.View.notifyKey(View.java:971)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```
