### ISSUE TITLE
java.lang.NullPointerException: Unknown

### ISSUE THREAD

**Issue by d954mas** [defold/editor2-issues#2566]
### Steps to reproduce
Don't know how two reproduce.
1)I have template
2)I have gui with 2 instances of template.
3)I moving them
4)Open template change size
5)press enter to accept changes then press ctrl+s. Not sure for what input get that error
6)Now ctrl+s always show that error.
7)In Gui files in editor i can't do anything(movement,changing and etc)
8)Close editor also not work(i think it try save changes but can't)
<hr/>

<table>
<tr><td>Build time</td><td>2019-04-17T18:28:30.387616</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>759189e7da3bb46f6a2655c10a2230e8ab48d4c4</td></tr>
<tr><td>Defold engine sha</td><td>e05232d70b8a6d8c69fcfe968f01b876090ffa06</td></tr>
<tr><td>Defold version</td><td>1.2.151</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"e0839e5658304c77ae9bee9eb4c4f1af"'>e0839e5658304c77ae9bee9eb4c4f1af</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1070 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 390.65</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment]
Hi! What do you mean by "I moving that instances" in step 3?

**Comment by matgis-king** [comment]
```
clojure.lang.Numbers.ops.class java.lang.NullPointerException: null
    at clojure.lang.Numbers.ops(Numbers.java:1068)
    at clojure.lang.Numbers.gt(Numbers.java:259)
    at clojure.lang.Numbers.gt(Numbers.java:3957)
    at editor.validation$prop_id_duplicate_QMARK_.invokeStatic(validation.clj:19)
    at editor.validation$prop_id_duplicate_QMARK_.invoke(validation.clj:18)
    at clojure.core$partial$fn.invoke(core.clj:2624)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.RestFn.applyTo(RestFn.java:132)
    at clojure.core$apply.invokeStatic(core.clj:667)
    at editor.validation$prop_error.invokeStatic(validation.clj:69)
    at editor.validation$prop_error.doInvoke(validation.clj:69)
    at clojure.lang.RestFn.invoke(RestFn.java:500)
    at editor.gui$prop_unique_id_error.invokeStatic(gui.clj:485)
    at editor.gui$fn.invokeStatic(gui.clj:545)
    at editor.gui$fn.invoke(gui.clj:545)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.gui$BoxNode$behavior$_declared_properties$fn.invoke(gui.clj:883)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$BoxNode$behavior$_declared_properties.invokeStatic(gui.clj:883)
    at editor.gui$BoxNode$behavior$_declared_properties.invoke(gui.clj:883)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1527)
    at editor.gui$BoxNode$behavior$node_msg$fn.invoke(gui.clj:883)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$BoxNode$behavior$node_msg.invokeStatic(gui.clj:883)
    at editor.gui$BoxNode$behavior$node_msg.invoke(gui.clj:883)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at editor.gui$BoxNode$behavior$node_msgs$fn.invoke(gui.clj:883)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$BoxNode$behavior$node_msgs.invokeStatic(gui.clj:883)
    at editor.gui$BoxNode$behavior$node_msgs.invoke(gui.clj:883)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at internal.node$pull_input_values$fn.invoke(node.clj:1124)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1125)
    at editor.gui$NodeTree$behavior$node_msgs$fn.invoke(gui.clj:1920)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$NodeTree$behavior$node_msgs.invokeStatic(gui.clj:1920)
    at editor.gui$NodeTree$behavior$node_msgs.invoke(gui.clj:1920)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1108)
    at editor.gui$GuiSceneNode$behavior$node_msgs$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$node_msgs.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$node_msgs.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at editor.gui$GuiSceneNode$behavior$pb_msg$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$pb_msg.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$pb_msg.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1108)
    at editor.gui$TemplateNode$behavior$node_msgs$fn.invoke(gui.clj:1242)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$TemplateNode$behavior$node_msgs.invokeStatic(gui.clj:1242)
    at editor.gui$TemplateNode$behavior$node_msgs.invoke(gui.clj:1242)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at internal.node$pull_input_values$fn.invoke(node.clj:1124)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1125)
    at editor.gui$BoxNode$behavior$node_msgs$fn.invoke(gui.clj:883)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$BoxNode$behavior$node_msgs.invokeStatic(gui.clj:883)
    at editor.gui$BoxNode$behavior$node_msgs.invoke(gui.clj:883)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at internal.node$pull_input_values$fn.invoke(node.clj:1124)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1125)
    at editor.gui$NodeTree$behavior$node_msgs$fn.invoke(gui.clj:1920)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$NodeTree$behavior$node_msgs.invokeStatic(gui.clj:1920)
    at editor.gui$NodeTree$behavior$node_msgs.invoke(gui.clj:1920)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1108)
    at editor.gui$GuiSceneNode$behavior$node_msgs$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$node_msgs.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$node_msgs.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at editor.gui$GuiSceneNode$behavior$pb_msg$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$pb_msg.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$pb_msg.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.OverrideNode.produce_value(node.clj:1555)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1108)
    at editor.gui$TemplateNode$behavior$node_msgs$fn.invoke(gui.clj:1242)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$TemplateNode$behavior$node_msgs.invokeStatic(gui.clj:1242)
    at editor.gui$TemplateNode$behavior$node_msgs.invoke(gui.clj:1242)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn.invoke(node.clj:1124)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1125)
    at editor.gui$BoxNode$behavior$node_msgs$fn.invoke(gui.clj:883)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$BoxNode$behavior$node_msgs.invokeStatic(gui.clj:883)
    at editor.gui$BoxNode$behavior$node_msgs.invoke(gui.clj:883)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn.invoke(node.clj:1124)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1125)
    at editor.gui$NodeTree$behavior$node_msgs$fn.invoke(gui.clj:1920)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$NodeTree$behavior$node_msgs.invokeStatic(gui.clj:1920)
    at editor.gui$NodeTree$behavior$node_msgs.invoke(gui.clj:1920)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1108)
    at editor.gui$GuiSceneNode$behavior$node_msgs$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$node_msgs.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$node_msgs.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$GuiSceneNode$behavior$pb_msg$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$pb_msg.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$pb_msg.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$GuiSceneNode$behavior$save_value$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$save_value.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$save_value.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$GuiSceneNode$behavior$save_data$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$save_data.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$save_data.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn.invoke(node.clj:1124)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1125)
    at editor.defold_project$Project$behavior$save_data$fn.invoke(defold_project.clj:559)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.defold_project$Project$behavior$save_data.invokeStatic(defold_project.clj:559)
    at editor.defold_project$Project$behavior$save_data.invoke(defold_project.clj:559)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.defold_project$Project$behavior$dirty_save_data$fn.invoke(defold_project.clj:559)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.defold_project$Project$behavior$dirty_save_data.invokeStatic(defold_project.clj:559)
    at editor.defold_project$Project$behavior$dirty_save_data.invoke(defold_project.clj:559)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$node_value.invokeStatic(node.clj:392)
    at internal.system$node_value.invokeStatic(system.clj:341)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:776)
    at dynamo.graph$node_value.invokeStatic(graph.clj:779)
    at editor.defold_project$dirty_save_data.invokeStatic(defold_project.clj:226)
    at editor.boot_open_project$load_stage$fn.invoke(boot_open_project.clj:223)
    at editor.ui$fn$fn.invoke(ui.clj:1939)
    at editor.ui$chain_handler$reify.handle(ui.clj:1925)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at com.sun.javafx.stage.WindowPeerListener.closing(WindowPeerListener.java:93)
    at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:147)
    at com.sun.javafx.tk.quantum.GlassWindowEventHandler.run(GlassWindowEventHandler.java:40)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassWindowEventHandler.lambda$handleWindowEvent$4(GlassWindowEventHandler.java:176)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
    at com.sun.javafx.tk.quantum.GlassWindowEventHandler.handleWindowEvent(GlassWindowEventHandler.java:174)
    at com.sun.glass.ui.Window.handleWindowEvent(Window.java:1346)
    at com.sun.glass.ui.Window.notifyClose(Window.java:1246)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by d954mas** [comment]
Hi. By moving I mean. That I change position of that GUI template, in main GUI scene
