### ISSUE TITLE
Null pointer exception after syncing

### ISSUE THREAD

**Issue by benjames-171** [defold/editor2-issues#2570]
### Expected behaviour
Synchronise project then close dialog box after clicking "done" 

### Actual behaviour
As above but the following error message is displayed -

**java.lang.NullPointerException: Unknown**

### Steps to reproduce
 Sychronize -> Pull -> Push ->Stage -> Push -> Done.... dialog closes and error message is displayed. It's only happened once so far.

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-24T16:55:26.072424</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>61f46cee8040eb233ecc7e328f8b6d97693f1f40</td></tr>
<tr><td>Defold engine sha</td><td>e05232d70b8a6d8c69fcfe968f01b876090ffa06</td></tr>
<tr><td>Defold version</td><td>1.2.151</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d448d3ef5f9046b78764060fb10a4a13"'>d448d3ef5f9046b78764060fb10a4a13</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 520</td></tr>
<tr><td>GPU Driver</td><td>4.5.0 - Build 25.20.100.6471</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
```
internal.graph$pre_traverse.invokeStatic.class java.lang.NullPointerException: null
    at internal.graph$pre_traverse.invokeStatic(graph.clj:522)
    at internal.graph$pre_traverse.doInvoke(graph.clj:509)
    at clojure.lang.RestFn.invoke(RestFn.java:445)
    at internal.transaction$populate_overrides$fn.invoke(transaction.clj:360)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at internal.transaction$populate_overrides.invokeStatic(transaction.clj:354)
    at internal.transaction$populate_overrides.invoke(transaction.clj:353)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at internal.transaction$populate_overrides$fn.invoke(transaction.clj:360)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at internal.transaction$populate_overrides.invokeStatic(transaction.clj:354)
    at internal.transaction$populate_overrides.invoke(transaction.clj:353)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at clojure.core$reduce.invoke(core.clj:6810)
    at clojure.core$partial$fn.invoke(core.clj:2625)
    at internal.transaction$fn.invokeStatic(transaction.clj:414)
    at internal.transaction$fn.invoke(transaction.clj:366)
    at clojure.lang.MultiFn.invoke(MultiFn.java:234)
    at internal.transaction$apply_tx$fn.invoke(transaction.clj:637)
    at internal.transaction$apply_tx.invokeStatic(transaction.clj:637)
    at internal.transaction$transact_STAR_.invokeStatic(transaction.clj:704)
    at dynamo.graph$transact.invokeStatic(graph.clj:131)
    at editor.defold_project$perform_resource_change_plan.invokeStatic(defold_project.clj:477)
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:533)
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:711)
    at editor.workspace$resource_sync_BANG_$fn.invoke(workspace.clj:310)
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:304)
    at editor.disk$start_reload_job_BANG_$fn$fn.invoke(disk.clj:71)
    at clojure.lang.AFn.run(AFn.java:22)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```
