### ISSUE TITLE
Error java.lang.NullPointerException: Unknown

### ISSUE THREAD

**Issue by AleksandrMiheev** [defold/editor2-issues#2572]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-24T16:55:26.072424</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>61f46cee8040eb233ecc7e328f8b6d97693f1f40</td></tr>
<tr><td>Defold engine sha</td><td>e05232d70b8a6d8c69fcfe968f01b876090ffa06</td></tr>
<tr><td>Defold version</td><td>1.2.151</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"588f26ebe603451c9e3c63137e9b4ef1"'>588f26ebe603451c9e3c63137e9b4ef1</a></td></tr>
<tr><td>GPU</td><td>GeForce GT 640/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 425.31</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<table>

**Comment by matgis-king** [comment]
```
javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7.class java.lang.NullPointerException: null
    at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by matgis-king** [comment]
Can you describe what you were doing when this occurred? Is it reproducible?

**Comment by NikDenissov** [comment]
Hi,

I've had the same error. I was modifying the game object's sphere shape in the collider.

Defold was running slow (for some reason I don't know yet). I've dragged the scale control of the object in the viewport, seen no effect and started clicking other tabs and components in the outline. After a couple of seconds Windows marked Defold as "not responding" app. And after a few more seconds Defold gave me this NullPointerException error.

I've worked on side scroller tutorial and had only readme.md and bonus_star.go opened in the editor.

Hope it will help.

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-30T13:25:18.384697</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b8b891be5ba3e650202848d8b84ddc2ca2ed513a</td></tr>
<tr><td>Defold engine sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold version</td><td>1.2.152</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"41aa2d18add74befb0801ab7153169bc"'>41aa2d18add74befb0801ab7153169bc</a></td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 4000</td></tr>
<tr><td>GPU Driver</td><td>4.0.0 - Build 10.18.10.4358</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by vlaaad** [comment]
JDK issue: [JDK-8179097](https://bugs.openjdk.java.net/browse/JDK-8179097). Reported 2017, yet unresolved..
