### ISSUE TITLE
Was setting clipping on a GUI node with a particlefx child

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2574]
Not sure if reproducible

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-29T14:42:28.192463</td></tr>
<tr><td>Defold channel</td><td>stable</td></tr>
<tr><td>Defold editor sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold engine sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold version</td><td>1.2.152</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d975a28a08ae4968bdd4362c11c79398"'>d975a28a08ae4968bdd4362c11c79398</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1060 6GB/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.39</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
```
javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7.class java.lang.NullPointerException: null
    at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by matgis-king** [comment]
Duplicate of #2572.
