### ISSUE TITLE
Opening Defold-examples main.collection, and errors

### ISSUE THREAD

**Issue by CocosGames** [defold/editor2-issues#2583]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-30T10:36:11.941822</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7680560c9ce42e98bc9c6764d7d5f25bd6c46c6a</td></tr>
<tr><td>Defold engine sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold version</td><td>1.2.152</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"b4f1104917cd4892a1755321f6fce882"'>b4f1104917cd4892a1755321f6fce882</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 660/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 417.35</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
```
javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7.class java.lang.NullPointerException: null
    at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by matgis-king** [comment]
Duplicate of #2572 and #2574.
