### ISSUE TITLE
java.security.PrivilegedActionException: Unknown

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2595]
### Expected behaviour
Error should be handled better

### Actual behaviour
java.security.PrivilegedActionException: Unknown
java.net.UnknownHostException: github.url.url.com

### Steps to reproduce
Bundle without Privilege

In my case I had forgotten to connect to the VPN

<hr/>

<table>
<tr><td>Build time</td><td>2019-05-07T09:50:29.752811</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>14212f327845c31295f296a33a1de5278836a85a</td></tr>
<tr><td>Defold engine sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold version</td><td>1.2.152</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"1f4e1abefbda4c30a1ae79a243ac17c1"'>1f4e1abefbda4c30a1ae79a243ac17c1</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by matgis-king** [comment]
(Sanitized URLs in Error Message)
```
java.security.AccessController.doPrivileged.class java.security.PrivilegedActionException: null
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
java.net.AbstractPlainSocketImpl.connect.class java.net.UnknownHostException: github.url.url.com
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:220)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.net.Socket.connect(Socket.java:591)
    at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:285)
    at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
    at sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
    at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:265)
    at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:372)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1181)
    at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1075)
    at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
    at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:163)
    at com.dynamo.bob.Project.resolveLibUrls(Project.java:1098)
    at editor.pipeline.bob$bob_build_BANG_$fn.invoke(bob.clj:126)
    at editor.pipeline.bob$bob_build_BANG_.invokeStatic(bob.clj:125)
    at editor.disk$async_bob_build_BANG_$fn$fn.invoke(disk.clj:182)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```
