### ISSUE TITLE
Error when opening a gui file

### ISSUE THREAD

**Issue by erikangelin-king** [defold/editor2-issues#2607]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-05-20T13:36:01.206153</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>b13a19230d5dcc61366b7a84aaff07599e2b393a</td></tr>
<tr><td>Defold engine sha</td><td>2a329c6cc44abfec727e985898d428d6860f658a</td></tr>
<tr><td>Defold version</td><td>1.2.154</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"9e550ac081cf46db86ea78e4cc3e1914"'>9e550ac081cf46db86ea78e4cc3e1914</a></td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.4.7</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.3</td></tr>
<table>

**Comment by matgis-king** [comment]
```
clojure.lang.Numbers.divide.class java.lang.NullPointerException: null
    at clojure.lang.Numbers.divide(Numbers.java:3885)
    at editor.font$get_texture_recip_uniform.invokeStatic(font.clj:359)
    at editor.gui$fn.invokeStatic(gui.clj:1162)
    at editor.gui$fn.invoke(gui.clj:1161)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.gui$TextNode$behavior$scene_renderable_user_data$fn.invoke(gui.clj:1120)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$TextNode$behavior$scene_renderable_user_data.invokeStatic(gui.clj:1120)
    at editor.gui$TextNode$behavior$scene_renderable_user_data.invoke(gui.clj:1120)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$TextNode$behavior$scene_outline_renderable$fn.invoke(gui.clj:1120)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$TextNode$behavior$scene_outline_renderable.invokeStatic(gui.clj:1120)
    at editor.gui$TextNode$behavior$scene_outline_renderable.invoke(gui.clj:1120)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$TextNode$behavior$scene$fn.invoke(gui.clj:1120)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$TextNode$behavior$scene.invokeStatic(gui.clj:1120)
    at editor.gui$TextNode$behavior$scene.invoke(gui.clj:1120)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn.invoke(node.clj:1145)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1146)
    at editor.gui$BoxNode$behavior$scene_children$fn.invoke(gui.clj:885)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$BoxNode$behavior$scene_children.invokeStatic(gui.clj:885)
    at editor.gui$BoxNode$behavior$scene_children.invoke(gui.clj:885)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$BoxNode$behavior$scene$fn.invoke(gui.clj:885)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$BoxNode$behavior$scene.invokeStatic(gui.clj:885)
    at editor.gui$BoxNode$behavior$scene.invoke(gui.clj:885)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn.invoke(node.clj:1145)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1146)
    at editor.gui$NodeTree$behavior$child_scenes$fn.invoke(gui.clj:1922)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$NodeTree$behavior$child_scenes.invokeStatic(gui.clj:1922)
    at editor.gui$NodeTree$behavior$child_scenes.invoke(gui.clj:1922)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$NodeTree$behavior$scene$fn.invoke(gui.clj:1922)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$NodeTree$behavior$scene.invokeStatic(gui.clj:1922)
    at editor.gui$NodeTree$behavior$scene.invoke(gui.clj:1922)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1129)
    at editor.gui$GuiSceneNode$behavior$child_scenes$fn.invoke(gui.clj:2192)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$child_scenes.invokeStatic(gui.clj:2192)
    at editor.gui$GuiSceneNode$behavior$child_scenes.invoke(gui.clj:2192)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$GuiSceneNode$behavior$scene$fn.invoke(gui.clj:2192)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.gui$GuiSceneNode$behavior$scene.invokeStatic(gui.clj:2192)
    at editor.gui$GuiSceneNode$behavior$scene.invoke(gui.clj:2192)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1129)
    at editor.scene$SceneView$behavior$scene_render_data$fn.invoke(scene.clj:716)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.scene$SceneView$behavior$scene_render_data.invokeStatic(scene.clj:716)
    at editor.scene$SceneView$behavior$scene_render_data.invoke(scene.clj:716)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.scene$SceneView$behavior$selected_aabb$fn.invoke(scene.clj:716)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.scene$SceneView$behavior$selected_aabb.invokeStatic(scene.clj:716)
    at editor.scene$SceneView$behavior$selected_aabb.invoke(scene.clj:716)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$node_value.invokeStatic(node.clj:413)
    at internal.system$node_value.invokeStatic(system.clj:341)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:793)
    at dynamo.graph$node_value.invokeStatic(graph.clj:796)
    at editor.scene$frame_selection.invokeStatic(scene.clj:898)
    at editor.scene$make_gl_pane_BANG_$fn$fn.invoke(scene.clj:1169)
    at editor.scene$make_gl_pane_BANG_$fn.invoke(scene.clj:1152)
    at editor.scene.proxy$com.defold.control.Region$ff19274a.layoutChildren
    at javafx.scene.Parent.layout(Parent.java:1206)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Parent.layout(Parent.java:1213)
    at javafx.scene.Scene.doLayoutPass(Scene.java:576)
    at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2482)
    at com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:412)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:411)
    at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:438)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:562)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:542)
    at com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:535)
    at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:341)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
```

**Comment by matgis-king** [comment]
Duplicate of #2566.
