### ISSUE TITLE
Bob: java.awt.image.RasterFormatException

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2609]
macOS 10.11.6

ERROR builtins/fonts/system_font.font:0 (y + height) is outside of Raster

```
java.awt.image.RasterFormatException: (y + height) is outside of Raster
	at sun.awt.image.ByteInterleavedRaster.createWritableChild(ByteInterleavedRaster.java:1248)
	at sun.awt.image.ByteInterleavedRaster.createChild(ByteInterleavedRaster.java:1208)
	at sun.java2d.pipe.GeneralCompositePipe.renderPathTile(GeneralCompositePipe.java:106)
	at sun.java2d.pipe.AAShapePipe.renderTiles(AAShapePipe.java:201)
	at sun.java2d.pipe.AAShapePipe.renderPath(AAShapePipe.java:159)
	at sun.java2d.pipe.AAShapePipe.fill(AAShapePipe.java:68)
	at sun.java2d.pipe.PixelToParallelogramConverter.fill(PixelToParallelogramConverter.java:164)
	at sun.java2d.pipe.ValidatePipe.fill(ValidatePipe.java:160)
	at sun.java2d.SunGraphics2D.fill(SunGraphics2D.java:2527)
	at com.dynamo.bob.font.Fontc.drawGlyph(Fontc.java:778)
	at com.dynamo.bob.font.Fontc.generateGlyphData(Fontc.java:496)
	at com.dynamo.bob.font.Fontc.compile(Fontc.java:857)
	at com.dynamo.bob.pipeline.FontBuilder.build(FontBuilder.java:53)
	at com.dynamo.bob.Project.runTasks(Project.java:949)
	at com.dynamo.bob.Project.doBuild(Project.java:750)
	at com.dynamo.bob.Project.build(Project.java:385)
	at com.dynamo.bob.Bob.main(Bob.java:543)
```

**Comment by Jerakin** [comment]
Works fine on windows. The build command is simply

`java -jar "D:\Repo\bob\1.2.154.jar" --archive --platform armv7-android --auth "" --email "" resolve build bundle`

**Comment by britzl** [comment]
Java related: https://forum.defold.com/t/error-game-project-0-java-heap-space-when-bundling-with-bob-jar/49127/2?u=britzl

**Comment by mathiaswking** [comment]
bob.jar requires Oracle's Java version 1.8

**Comment by Jerakin** [comment]
Currently I have this installed - So I guess that version doesn't work
```
openjdk version "1.8.0_22"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
OpenJDK 64-Bit Server VM AdoptOpenJDK)(build 1.8.0_212-b03, mixed mode)
```
