### ISSUE TITLE
Bob: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2610]
Windows
```
java.lang.OutOfMemoryError: Java heap space
        at com.google.protobuf.ByteString.toByteArray(ByteString.java:201)
        at com.google.protobuf.CodedOutputStream.writeBytesNoTag(CodedOutputStream.java:384)
        at com.google.protobuf.CodedOutputStream.writeBytes(CodedOutputStream.java:228)
        at com.dynamo.graphics.proto.Graphics$TextureImage$Image.writeTo(Unknown Source)
        at com.google.protobuf.CodedOutputStream.writeMessageNoTag(CodedOutputStream.java:379)
        at com.google.protobuf.CodedOutputStream.writeMessage(CodedOutputStream.java:221)
        at com.dynamo.graphics.proto.Graphics$TextureImage.writeTo(Unknown Source)
        at com.google.protobuf.AbstractMessageLite.toByteArray(AbstractMessageLite.java:64)
        at com.dynamo.bob.pipeline.AtlasBuilder.build(AtlasBuilder.java:77)
        at com.dynamo.bob.Project.runTasks(Project.java:949)
        at com.dynamo.bob.Project.doBuild(Project.java:750)
        at com.dynamo.bob.Project.build(Project.java:385)
        at com.dynamo.bob.Bob.main(Bob.java:543)
```

**Comment by Jerakin** [comment]
Accidentally ran bob with a 32bit java
