### ISSUE TITLE
Java.lang.IndexOutOfBoundsException:Unknown | After idle (Instance 1)

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2612]
Left work with the computer running two Defold Engine instances and one instance of a running game and came back to this the morning after (~16 hours after)

(Both engines threw the error reporting both just incase)

<hr/>

<table>
<tr><td>Build time</td><td>2019-05-17T14:30:43.003830</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>1a06f0197d99273a997ad723832703ccccf53886</td></tr>
<tr><td>Defold engine sha</td><td>2a329c6cc44abfec727e985898d428d6860f658a</td></tr>
<tr><td>Defold version</td><td>1.2.154</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"d95ccf9c8b4d4b148825c36693c16edc"'>d95ccf9c8b4d4b148825c36693c16edc</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-1.60.26</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.13.3</td></tr>
<table>

**Comment by matgis-king** [comment]
```
java.io.BufferedInputStream.read.class java.lang.IndexOutOfBoundsException: null
    at java.io.BufferedInputStream.read(BufferedInputStream.java:344)
    at sun.net.httpserver.ChunkedInputStream.readImpl(ChunkedInputStream.java:130)
    at sun.net.httpserver.LeftOverInputStream.read(LeftOverInputStream.java:99)
    at java.io.FilterInputStream.read(FilterInputStream.java:107)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1792)
    at org.apache.commons.io.IOUtils.copyLarge(IOUtils.java:1769)
    at org.apache.commons.io.IOUtils.copy(IOUtils.java:1744)
    at util.http_server$exchange__GT_request_BANG_.invokeStatic(http_server.clj:20)
    at util.http_server$setup_server_BANG_$reify.handle(http_server.clj:49)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
    at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
    at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:442)
    at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408)
    at java.lang.Thread.run(Thread.java:834)
```
