### ISSUE TITLE
renaming gui element after deleting it and recreating it

### ISSUE THREAD

**Issue by fiftywalrus** [defold/editor2-issues#2615]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-04-15T12:47:21.127828</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>95ffa569158e21afb0cfd1697de60133bc71f843</td></tr>
<tr><td>Defold engine sha</td><td>e05232d70b8a6d8c69fcfe968f01b876090ffa06</td></tr>
<tr><td>Defold version</td><td>1.2.151</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"f77d8e3506a2459b9115eac9fd150524"'>f77d8e3506a2459b9115eac9fd150524</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 970/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.13</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
```
java.lang.String.substring.class java.lang.StringIndexOutOfBoundsException: String index out of range: -3
    at java.lang.String.substring(String.java:1841)
    at clojure.core$subs.invokeStatic(core.clj:4986)
    at editor.gui$fn$fn.invoke(gui.clj:1254)
    at clojure.core$map$fn.invoke(core.clj:2755)
    at clojure.lang.LazySeq.sval(LazySeq.java:42)
    at clojure.lang.LazySeq.seq(LazySeq.java:51)
    at clojure.lang.RT.seq(RT.java:531)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at clojure.core$into.invokeStatic(core.clj:6895)
    at editor.gui$fn.invokeStatic(gui.clj:1253)
    at editor.gui$fn.invoke(gui.clj:1253)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.gui$TemplateNode$behavior$_declared_properties$fn.invoke(gui.clj:1242)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.gui$TemplateNode$behavior$_declared_properties.invokeStatic(gui.clj:1242)
    at editor.gui$TemplateNode$behavior$_declared_properties.invoke(gui.clj:1242)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$TemplateNode$behavior$node_msg$fn.invoke(gui.clj:1242)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.gui$TemplateNode$behavior$node_msg.invokeStatic(gui.clj:1242)
    at editor.gui$TemplateNode$behavior$node_msg.invoke(gui.clj:1242)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$TemplateNode$behavior$node_msgs$fn.invoke(gui.clj:1242)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.gui$TemplateNode$behavior$node_msgs.invokeStatic(gui.clj:1242)
    at editor.gui$TemplateNode$behavior$node_msgs.invoke(gui.clj:1242)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn.invoke(node.clj:1124)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1125)
    at editor.gui$NodeTree$behavior$node_msgs$fn.invoke(gui.clj:1920)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.gui$NodeTree$behavior$node_msgs.invokeStatic(gui.clj:1920)
    at editor.gui$NodeTree$behavior$node_msgs.invoke(gui.clj:1920)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1108)
    at editor.gui$GuiSceneNode$behavior$node_msgs$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.gui$GuiSceneNode$behavior$node_msgs.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$node_msgs.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$GuiSceneNode$behavior$pb_msg$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.gui$GuiSceneNode$behavior$pb_msg.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$pb_msg.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$GuiSceneNode$behavior$save_value$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.gui$GuiSceneNode$behavior$save_value.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$save_value.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.gui$GuiSceneNode$behavior$save_data$fn.invoke(gui.clj:2190)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.gui$GuiSceneNode$behavior$save_data.invokeStatic(gui.clj:2190)
    at editor.gui$GuiSceneNode$behavior$save_data.invoke(gui.clj:2190)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn.invoke(node.clj:1124)
    at clojure.core$mapv$fn.invoke(core.clj:6912)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$reduce.invokeStatic(core.clj:6827)
    at clojure.core$mapv.invokeStatic(core.clj:6903)
    at internal.node$pull_input_values.invokeStatic(node.clj:1125)
    at editor.defold_project$Project$behavior$save_data$fn.invoke(defold_project.clj:559)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.defold_project$Project$behavior$save_data.invokeStatic(defold_project.clj:559)
    at editor.defold_project$Project$behavior$save_data.invoke(defold_project.clj:559)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.defold_project$Project$behavior$dirty_save_data$fn.invoke(defold_project.clj:559)
    at internal.node$trace_expr$fn.invoke(node.clj:23)
    at internal.node$trace_expr.invokeStatic(node.clj:23)
    at editor.defold_project$Project$behavior$dirty_save_data.invokeStatic(defold_project.clj:559)
    at editor.defold_project$Project$behavior$dirty_save_data.invoke(defold_project.clj:559)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$node_value.invokeStatic(node.clj:392)
    at internal.system$node_value.invokeStatic(system.clj:341)
    at dynamo.graph$do_node_value.invokeStatic(graph.clj:776)
    at dynamo.graph$node_value.invokeStatic(graph.clj:779)
    at editor.defold_project$dirty_save_data.invokeStatic(defold_project.clj:226)
    at editor.defold_project$dirty_save_data_with_progress.invokeStatic(defold_project.clj:241)
    at editor.disk$start_save_job_BANG_$fn.invoke(disk.clj:119)
    at clojure.core$binding_conveyor_fn$fn.invoke(core.clj:2030)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by vlaaad** [comment]
We were unable to reproduce the issue by recreating gui element and renaming it, can you share a repro project?
