### ISSUE TITLE
bundle iOS error

### ISSUE THREAD

**Issue by fendorio** [defold/editor2-issues#2631]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-05-07T09:45:02.194789</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>d06eafc5a944bc139a6bfc2710993fd9dbe6ff3e</td></tr>
<tr><td>Defold engine sha</td><td>11b1e7662dd68172fca551c52cba248eea16a364</td></tr>
<tr><td>Defold version</td><td>1.2.152</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"3a959464aa3540faab5e240741e2b529"'>3a959464aa3540faab5e240741e2b529</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560X OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.8.38</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.4</td></tr>
<table>

**Comment by matgis-king** [comment]
```
javafx.scene.Scene$ScenePeerListener.zoomEvent.class java.lang.NullPointerException: null
    at javafx.scene.Scene$ScenePeerListener.zoomEvent(Scene.java:2691)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleZoomGestureEvent$18(GlassViewEventHandler.java:1063)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleZoomGestureEvent$19(GlassViewEventHandler.java:1028)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleZoomGestureEvent(GlassViewEventHandler.java:1027)
    at com.sun.glass.ui.View.handleZoomGestureEvent(View.java:612)
    at com.sun.glass.ui.View.notifyZoomGestureEvent(View.java:1080)
    at com.sun.glass.ui.GestureSupport.handleZoomingEnd(GestureSupport.java:166)
    at com.sun.glass.ui.GestureSupport.lambda$createTouchCountListener$0(GestureSupport.java:396)
    at com.sun.glass.ui.TouchInputSupport.notifyEndTouchEvent(TouchInputSupport.java:115)
    at com.sun.glass.ui.mac.MacTouchInputSupport.notifyEndTouchEvent(MacTouchInputSupport.java:93)
    at com.sun.glass.ui.mac.MacGestureSupport.notifyEndTouchEvent(MacGestureSupport.java:81)
```
