### ISSUE TITLE
Crash dmengine.exe

### ISSUE THREAD

**Issue by wkqco33** [defold/editor2-issues#2644]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-06-11T09:20:36.620492</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4fe1a4135c842ac05bff8e1fc28884296052a3e2</td></tr>
<tr><td>Defold engine sha</td><td>67b68f1e1ac26a3385fb511cdce520fe52387bb0</td></tr>
<tr><td>Defold version</td><td>1.2.156</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"6e32aa36ee564631af2e0b5659d30a75"'>6e32aa36ee564631af2e0b5659d30a75</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 1050 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.86</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by markusgustavssonking** [comment]
Connection timeout. I guess because of engine crash? 
If you can supply a little more information about what you were doing or even a reproduction case project we might be able to look into why it crashed.
```
java.net.PlainSocketImpl.waitForConnect.class java.net.SocketTimeoutException: connect timed out
    at java.net.PlainSocketImpl.waitForConnect(PlainSocketImpl.java)
    at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
    at java.net.Socket.connect(Socket.java:591)
    at editor.debugging.mobdebug$try_connect_BANG_.invokeStatic(mobdebug.clj:279)
    at editor.debugging.mobdebug$connect_BANG_$fn.invoke(mobdebug.clj:284)
    at clojure.lang.AFn.run(AFn.java:22)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.util.concurrent.FutureTask.run(FutureTask.java:264)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by wkqco33** [comment]
Thank you for your help, I guess there was a temporary issue.
