### ISSUE TITLE
Minor error when trying to build colorslide tutorial

### ISSUE THREAD

**Issue by rpersaud** [defold/editor2-issues#2693]
### Expected behaviour
Clicked around menus to find where to build and run the game

### Actual behaviour
Encountered dialog with error and dismissed to continue finding menu to build and run locally the tutorial

### Steps to reproduce

1.Started colorslide tutorial
2.Clicked around menu's to build
3. Encountered java error, dismissed

<hr/>

<table>
<tr><td>Build time</td><td>2019-07-30T16:50:09.989230</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>5dd02a32a775ec61aac42fdf2b2e7a03cd0c6d68</td></tr>
<tr><td>Defold engine sha</td><td>f7d0a1ba6940e42c7f7e1c208ba484c3c34a135d</td></tr>
<tr><td>Defold version</td><td>1.2.159</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"a3016e50294f4797be48d4313604da60"'>a3016e50294f4797be48d4313604da60</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 750 Ti/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 430.86</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
```
javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7.class java.lang.NullPointerException: null
    at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by matgis-king** [comment]
#2590
