### ISSUE TITLE
Error when clicking on a tab while auto-complete is active

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#2695]
### Expected behaviour
I should be able to change tab even if I'm currently having auto-complete suggestions visible

### Actual behaviour
If I have auto-complete suggestions available and click on another tab in the editor I get an error

### Steps to reproduce
Trigger an auto-complete suggestion and click on another tab
<hr/>

<table>
<tr><td>Build time</td><td>2019-07-26T10:28:48.426545</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6d8f9ccd1cb4896691ab5e2d9bc98f2a587b7556</td></tr>
<tr><td>Defold engine sha</td><td>f7d0a1ba6940e42c7f7e1c208ba484c3c34a135d</td></tr>
<tr><td>Defold version</td><td>1.2.159</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ee89c5d8508d472eb60a5bfa5b393848"'>ee89c5d8508d472eb60a5bfa5b393848</a></td></tr>
<tr><td>GPU</td><td>NVIDIA GeForce GT 750M OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 NVIDIA-12.0.23 355.11.10.50.10.103</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.5</td></tr>
<table>

**Comment by AGulev** [comment]
I got the same exception many times, but can't figure out the reason. Cool that you caught it!

**Comment by matgis-king** [comment]
Duplicate of #2693, #2590, #2583, #2574, #2572 with good repro!

**Comment by matgis-king** [comment]
```
javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7.class java.lang.NullPointerException: null
    at javafx.scene.control.skin.MenuButtonSkinBase.lambda$new$7(MenuButtonSkinBase.java:188)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:428)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:427)
    at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```
