### ISSUE TITLE
Colorslide tutorial | The level selection screen | Construct an interface with 4 buttons

### ISSUE THREAD

**Issue by JoeKlemmer** [defold/editor2-issues#2696]
### Expected behaviour
Step 7. Set the Texture of the node to bricks/button.

Following the tutorial, this step should allow setting the texture to the indicated file.

### Actual behaviour

The file is not available as a dropdown option and, when attempting to manually set the filename, the editor threw a Javascript error.  The engine did not crash.

![Annotation 2019-08-03 112504](https://user-images.githubusercontent.com/40077917/62413820-782d1400-b5e1-11e9-83cd-e3c3b55ba6df.png)

### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-07-26T10:29:48.908428</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>6d8f9ccd1cb4896691ab5e2d9bc98f2a587b7556</td></tr>
<tr><td>Defold engine sha</td><td>f7d0a1ba6940e42c7f7e1c208ba484c3c34a135d</td></tr>
<tr><td>Defold version</td><td>1.2.159</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"f54063701f75494f8eb4d9c522b116bd"'>f54063701f75494f8eb4d9c522b116bd</a></td></tr>
<tr><td>GPU</td><td>GeForce GTX 560M/PCIe/SSE2</td></tr>
<tr><td>GPU Driver</td><td>4.6.0 NVIDIA 388.73</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>OS name</td><td>Windows 10</td></tr>
<tr><td>OS version</td><td>10.0</td></tr>
<table>

**Comment by matgis-king** [comment]
```
javafx.scene.control.skin.TabPaneSkin.stopDrag.class java.lang.NullPointerException: null
    at javafx.scene.control.skin.TabPaneSkin.stopDrag(TabPaneSkin.java:2197)
    at javafx.scene.control.skin.TabPaneSkin.handleHeaderMouseReleased(TabPaneSkin.java:2025)
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
    at javafx.event.Event.fireEvent(Event.java:198)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3862)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2590)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:411)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.win.WinApplication._runLoop(WinApplication.java)
    at com.sun.glass.ui.win.WinApplication.lambda$runLoop$3(WinApplication.java:174)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by matgis-king** [comment]
Hi! The error you got is an internal error in the JavaFx user-interface framework we use in the editor. It happens intermittently, but is unrelated to what you were doing. We're in the process of trying to get a fix into JavaFx.

However, the reason the texture was not available to select could be that you missed a step in the tutorial. It says in the Level Selection Screen section that you need to "Add the "bricks" atlas to the Textures section of the GUI", but this information is before the numbered steps so is easily missed.

**Comment by matgis-king** [comment]
Duplicate of #2692.

**Comment by JoeKlemmer** [comment]
On Mon, Aug 5, 2019 at 4:25 AM Mats Gisselson <notifications@github.com>
wrote:

> Hi! The error you got is an internal error in the JavaFx user-interface
> framework we use in the editor. It happens intermittently, but is unrelated
> to what you were doing. We're in the process of trying to get a fix into
> JavaFx.
>
Good to know, thank you.

> However, the reason the texture was not available to select could be that
> you missed a step in the tutorial. It says in the Level Selection Screen
> section that you need to "Add the "bricks" atlas to the Textures section of
> the GUI", but this information is before the numbered steps so is easily
> missed.
>
That's quite possible. Wouldn't be the first time I've done that. :-)

This section of the tutorial is a little fuzzy, though. It starts to get a
little less specific in the instructions such that one has to infer/guess
what exactly they need to do.

I must say I am enjoying Defold. Between using Lua and the design of the
editor, it has a very nice feel.

-- 


*Joe Klemmer*

*[image: https://]about.me/joeklemmer
<https://about.me/joeklemmer?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=gmail_api&utm_content=plaintext>*
