### ISSUE TITLE
Hit build after requiring new lua module.

### ISSUE THREAD

**Issue by nebreywas** [defold/editor2-issues#2702]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-06-11T09:19:24.991253</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4fe1a4135c842ac05bff8e1fc28884296052a3e2</td></tr>
<tr><td>Defold engine sha</td><td>67b68f1e1ac26a3385fb511cdce520fe52387bb0</td></tr>
<tr><td>Defold version</td><td>1.2.156</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"ce9b320e00404344b7ff11c9a00d54a4"'>ce9b320e00404344b7ff11c9a00d54a4</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 460 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.8.38</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.4</td></tr>
<table>

**Comment by matgis-king** [comment]
```
sun.net.httpserver.ExchangeImpl.bytes.class java.lang.NullPointerException: null
    at sun.net.httpserver.ExchangeImpl.bytes(ExchangeImpl.java:305)
    at sun.net.httpserver.ExchangeImpl.write(ExchangeImpl.java:285)
    at sun.net.httpserver.ExchangeImpl.sendResponseHeaders(ExchangeImpl.java:260)
    at sun.net.httpserver.HttpExchangeImpl.sendResponseHeaders(HttpExchangeImpl.java:85)
    at util.http_server$response__GT_exchange_BANG_.invokeStatic(http_server.clj:36)
    at util.http_server$setup_server_BANG_$reify.handle(http_server.clj:49)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
    at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
    at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:442)
    at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408)
    at java.lang.Thread.run(Thread.java:834)
```

**Comment by matgis-king** [comment]
It looks like something went wrong when we tried to communicate with the running game. Possibly a network issue. Does it happen every time you build?

**Comment by nebreywas** [comment]
Not sure. I think it was due to a stupid require command to a module sitting in said module as I didn’t notice I hadn’t switched windows. I could probably recreate. 

Ben

I am traveling at the moment.  This email is sent from my mobile device.
