### ISSUE TITLE
Error popups every time, I have no idea why.

### ISSUE THREAD

**Issue by reinardpalomo** [defold/editor2-issues#2703]
### Steps to reproduce

<hr/>

<table>
<tr><td>Build time</td><td>2019-07-18T09:58:06.110209</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>bf5d0bc6a9475389fd41889ef44e81f1f6a45dba</td></tr>
<tr><td>Defold engine sha</td><td>3d63d0509cc828c9555afc149cccfea0f7f83c97</td></tr>
<tr><td>Defold version</td><td>1.2.158</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"bb47dea02e644dd3bccd7fb43c2755b6"'>bb47dea02e644dd3bccd7fb43c2755b6</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.11.20</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.6</td></tr>
<table>

**Comment by matgis-king** [comment]
Every time you do what? Can you provide more information about what you were doing when the error occurred?

**Comment by matgis-king** [comment]
Callstack from report:
```
sun.net.httpserver.FixedLengthOutputStream.close.class java.io.IOException: insufficient bytes written to stream
    at sun.net.httpserver.FixedLengthOutputStream.close(FixedLengthOutputStream.java:89)
    at sun.net.httpserver.PlaceholderOutputStream.close(ExchangeImpl.java:455)
    at util.http_server$response__GT_exchange_BANG_$fn.invoke(http_server.clj:38)
    at util.http_server$response__GT_exchange_BANG_.invokeStatic(http_server.clj:38)
    at util.http_server$setup_server_BANG_$reify.handle(http_server.clj:49)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:80)
    at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:692)
    at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:77)
    at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:664)
    at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:159)
    at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:442)
    at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:408)
    at java.lang.Thread.run(Thread.java:834)
```
