### ISSUE TITLE
Editor exception on making spine scene from spine 3.8 json export

### ISSUE THREAD

**Issue by dyukorev** [defold/editor2-issues#2704]
### Expected behaviour
Spine scene creates

### Actual behaviour
Exception on adding json to spine scene

### Steps to reproduce
Try to set json file exported from Spine v3.8 to spinescene in defold editor 
[firework_front.json.zip](https://github.com/defold/editor2-issues/files/3506550/firework_front.json.zip)
<hr/>

<table>
<tr><td>Build time</td><td>2019-08-12T16:15:33.377166</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>4bc11628c8997a6b804f9abf42716d71979ffffe</td></tr>
<tr><td>Defold engine sha</td><td>f7d0a1ba6940e42c7f7e1c208ba484c3c34a135d</td></tr>
<tr><td>Defold version</td><td>1.2.159</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=id%3A"60df981c3b894e9a9c7be718e0bdeeb0"'>60df981c3b894e9a9c7be718e0bdeeb0</a></td></tr>
<tr><td>GPU</td><td>Intel Iris Pro OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-12.8.38</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14.4</td></tr>
<table>

**Comment by vlaaad** [comment]
```
clojure.lang.RT.seqFrom.class java.lang.IllegalArgumentException: Don't know how to create ISeq from: java.lang.Character
    at clojure.lang.RT.seqFrom(RT.java:553)
    at clojure.lang.RT.seq(RT.java:533)
    at clojure.core$seq__5387.invokeStatic(core.clj:137)
    at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:24)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$transduce.invokeStatic(core.clj:6884)
    at clojure.core$into.invokeStatic(core.clj:6899)
    at editor.spine$read_base_slots$fn.invoke(spine.clj:544)
    at clojure.core$map$fn$fn.invoke(core.clj:2742)
    at clojure.core$preserving_reduced$fn.invoke(core.clj:7614)
    at clojure.core.protocols$iter_reduce.invokeStatic(protocols.clj:49)
    at clojure.core.protocols$fn.invokeStatic(protocols.clj:75)
    at clojure.core.protocols$fn.invoke(protocols.clj:75)
    at clojure.core.protocols$fn$G__8068__8086.invoke(protocols.clj:13)
    at clojure.core$reduce.invokeStatic(core.clj:6828)
    at clojure.core$cat$fn.invoke(core.clj:7625)
    at clojure.core$map$fn$fn.invoke(core.clj:2742)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:343)
    at clojure.core$transduce.invokeStatic(core.clj:6883)
    at editor.spine$read_base_slots.invokeStatic(spine.clj:541)
    at editor.spine$fn.invokeStatic(spine.clj:640)
    at editor.spine$fn.invoke(spine.clj:634)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:384)
    at editor.spine$SpineSceneNode$behavior$spine_scene_pb$fn.invoke(spine.clj:886)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.spine$SpineSceneNode$behavior$spine_scene_pb.invokeStatic(spine.clj:886)
    at editor.spine$SpineSceneNode$behavior$spine_scene_pb.invoke(spine.clj:886)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.spine$SpineSceneNode$behavior$aabb$fn.invoke(spine.clj:886)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.spine$SpineSceneNode$behavior$aabb.invokeStatic(spine.clj:886)
    at editor.spine$SpineSceneNode$behavior$aabb.invoke(spine.clj:886)
    at clojure.lang.Var.invoke(Var.java:393)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.spine$SpineSceneNode$behavior$scene$fn.invoke(spine.clj:886)
    at internal.node$trace_expr.invokeStatic(node.clj:29)
    at editor.spine$SpineSceneNode$behavior$scene.invokeStatic(spine.clj:886)
    at editor.spine$SpineSceneNode$behavior$scene.invoke(spine.clj:886)
```

**Comment by matgis-king** [comment]
Looks like they changed the exported file format significantly in Spine 3.8. It is currently unclear how much work it would be to get scenes exported from Spine 3.8 working in Defold. We recommend you roll back Spine to 3.7 while we investigate.

**Comment by subsoap** [comment]
@matgis-king do you know the specific last known version supported? 3.7. ...?

**Comment by matgis-king** [comment]
The change happened in 3.8. I believe latest 3.7 should work?

**Comment by subsoap** [comment]
I will test 3.7.94 now, the last 3.7 version.

**Comment by subsoap** [comment]
Tested loading a project and exporting it with 3.7.94 and the skeleton.json from that does appear to work without issue. But I can't test the owl project because I don't have a copy of that that wasn't saved in a later version of Spine...

**Comment by matgis-king** [comment]
I tested loading the owl project in our work-in-progress branch where Spine 3.8 is supported, and it appears to load correctly. Some work still remains on bundling, but hopefully the fix should make it into the next Defold release.
