### ISSUE TITLE
Error when dragging and hover image over .md file

### ISSUE THREAD

**Issue by Jerakin** [defold/editor2-issues#2771]
### Steps to reproduce
_Something like_
1. New project
2. Drag image from finder
3. Place mouse cursor over README.md
4. Wait a bit

<hr/>

<table>
<tr><td>Build time</td><td>2019-09-24T14:18:18.918026</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>7c1a314b318aa7ea6de887b6a314c03c7b161464</td></tr>
<tr><td>Defold engine sha</td><td>e07f3bb9e8c970eceda8dce8efd5905fd67fa720</td></tr>
<tr><td>Defold version</td><td>1.2.162</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/organizations/defold/issues/?query=id%3A"c50510f58d3947cfbfe6c10fff1fa80a"'>c50510f58d3947cfbfe6c10fff1fa80a</a></td></tr>
<tr><td>GPU</td><td>AMD Radeon Pro 560 OpenGL Engine</td></tr>
<tr><td>GPU Driver</td><td>2.1 ATI-2.0.36</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.14</td></tr>
<table>

**Comment by matgis-king** [comment]
Duplicate of #1791, #1874, #1948, #2315, #2438.
```
com.sun.glass.ui.View$2.flush.class java.lang.UnsupportedOperationException: Flush is forbidden from target!
    at com.sun.glass.ui.View$2.flush(View.java:1022)
    at com.sun.javafx.tk.quantum.QuantumClipboard.flush(QuantumClipboard.java:274)
    at com.sun.javafx.tk.quantum.QuantumToolkit.startDrag(QuantumToolkit.java:1286)
    at javafx.scene.Scene$DnDGesture.dragDetectedProcessed(Scene.java:3049)
    at javafx.scene.Scene$DnDGesture.process(Scene.java:3118)
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3878)
    at javafx.scene.Scene.processMouseEvent(Scene.java:1849)
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2590)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:409)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:299)
    at java.security.AccessController.doPrivileged(AccessController.java)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:447)
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:412)
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:446)
    at com.sun.glass.ui.View.handleMouseEvent(View.java:556)
    at com.sun.glass.ui.View.notifyMouse(View.java:942)
    at com.sun.glass.ui.mac.MacView.notifyMouse(MacView.java:127)
```
