### ISSUE TITLE
strip_ios is called when bundling a macOS build on Windows with bob

### ISSUE THREAD

**Issue by subsoap** [defold/editor2-issues#2850]
```
[Bundling x86_64-darwin]
x86_64-darwin
Exception in thread "main" com.dynamo.bob.CompileExceptionError: Cannot run program "C:\Users\subso\AppData\Local\Temp\14294280906712658070\x86_64-darwin\strip_ios": CreateProcess error=193, %1 is not a valid Win32 application
        at com.dynamo.bob.Project.build(Project.java:448)
        at com.dynamo.bob.Bob.main(Bob.java:558)
Caused by: java.io.IOException: Cannot run program "C:\Users\subso\AppData\Local\Temp\14294280906712658070\x86_64-darwin\strip_ios": CreateProcess error=193, %1 is not a valid Win32 application
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
        at com.dynamo.bob.util.Exec.execResult(Exec.java:50)
        at com.dynamo.bob.bundle.OSXBundler.bundleApplication(OSXBundler.java:131)
        at com.dynamo.bob.Project.bundle(Project.java:589)
        at com.dynamo.bob.Project.doBuild(Project.java:896)
        at com.dynamo.bob.Project.build(Project.java:438)
        ... 1 more
Caused by: java.io.IOException: CreateProcess error=193, %1 is not a valid Win32 application
        at java.base/java.lang.ProcessImpl.create(Native Method)
        at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:420)
        at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:151)
        at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
        ... 7 more
```

**Comment by britzl** [comment]
This has been fixed in bob and will be included in the next release. A bob alpha is available here:

http://d.defold.com/archive/a237a1018ea606d34f18b0d3fb5dbef36d20d76d/bob/bob.jar
