### ISSUE TITLE
Can't build on MacOS

### ISSUE THREAD

**Issue by JamesOrson** [defold/editor2-issues#2921]
### Expected behaviour
Building on macOS should create an executable.

### Actual behaviour
Build fails in Defold. If using Bob.jar from the command line like so
```bash
java -jar Bob.jar
```
an exception is encountered
```
Exception in thread "main" com.dynamo.bob.CompileExceptionError: 'x86_64-osx' could not be built. Sdk version: '6fac6e80f09ab297093e3ff65a7f45ad56e06e33'
Log: '<failed reading log>'
	at com.dynamo.bob.bundle.BundleHelper.buildEngineRemote(BundleHelper.java:1106)
	at com.dynamo.bob.Project.buildEngine(Project.java:698)
	at com.dynamo.bob.Project.doBuild(Project.java:819)
	at com.dynamo.bob.Project.build(Project.java:441)
	at com.dynamo.bob.Bob.main(Bob.java:569)
Caused by: javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:645)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:464)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:360)
	at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
	at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:421)
	at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:177)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:164)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1151)
	at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1062)
	at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:402)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:553)
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:412)
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:179)
	at org.apache.http.impl.conn.ManagedClientConnectionImpl.open(ManagedClientConnectionImpl.java:328)
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:612)
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:447)
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at com.defold.extender.client.ExtenderClient.queryCache(ExtenderClient.java:93)
	at com.defold.extender.client.ExtenderClient.build(ExtenderClient.java:153)
	at com.dynamo.bob.bundle.BundleHelper.buildEngineRemote(BundleHelper.java:1044)
	... 4 more
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:369)
	at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:275)
	at java.base/sun.security.validator.Validator.validate(Validator.java:264)
	at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:222)
	at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:129)
	at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:629)
	... 27 more
Caused by: java.security.cert.CertPathValidatorException: validity check failed
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:237)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:145)
	at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:84)
	at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
	at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:364)
	... 33 more
Caused by: java.security.cert.CertificateExpiredException: NotAfter: Fri Feb 28 04:00:00 PST 2020
	at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
	at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:675)
	at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
	at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
	at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 38 more
```

### Steps to reproduce
Build a project on MacOS Catalina with OpenJDK 11.

<hr/>

<table>
<tr><td>Build time</td><td>2020-02-24T13:25:40.151825</td></tr>
<tr><td>Defold channel</td><td>editor-alpha</td></tr>
<tr><td>Defold editor sha</td><td>9bdf3bb078a30c2c8589b6c096d372c104b032f5</td></tr>
<tr><td>Defold engine sha</td><td>6fac6e80f09ab297093e3ff65a7f45ad56e06e33</td></tr>
<tr><td>Defold version</td><td>1.2.165</td></tr>
<tr><td>GPU</td><td>Intel(R) HD Graphics 6000</td></tr>
<tr><td>GPU Driver</td><td>2.1 INTEL-14.4.23</td></tr>
<tr><td>Java version</td><td>11.0.1+13</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.15.3</td></tr>
<table>

**Comment by JCash** [comment]
Yes, we unfortunately have a cert that expired, and we’re hoping to resolve that issue tomorrow.

**Comment by subsoap** [comment]
Working now?

**Comment by britzl** [comment]
The certificates have been updated. Closing.
