### ISSUE TITLE
Cant add game object to collection file

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#294]
1. Create a new collection (level.collection)
2. Add a collection from file in it (ground.collection)
3. Add a game object from file in the level collection (hero.go)

Actual result:
Cant add hero.go to level.collection
Nothing happens in the editor, no feedback on why.

Adding a game object not from a file works.

2016-12-08 16:14:49.600 1181049 [JavaFX Application Thread] ERROR editor.handler - {:line 49, :msg "handler :add-from-file in context :workbench failed at :run with message [Wrong number of args (3) passed to: collection/add-game-object-file]"}
clojure.lang.ArityException: Wrong number of args (3) passed to: collection/add-game-object-file
	at clojure.lang.AFn.throwArity(AFn.java:429) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at clojure.lang.AFn.invoke(AFn.java:40) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at editor.collection$fn__56394$fnk56389_positional__56395.invoke(collection.clj:660) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at editor.collection$fn__56394$fnk56389__56409$fn__56410.invoke(collection.clj:654) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at editor.collection$fn__56394$fnk56389__56409.invoke(collection.clj:654) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at clojure.lang.AFn.applyToHelper(AFn.java:154) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at clojure.lang.AFn.applyTo(AFn.java:144) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at clojure.lang.RestFn.invoke(RestFn.java:408) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at editor.handler$invoke_fnk.invokeStatic(handler.clj:47) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at editor.handler$run.invokeStatic(handler.clj:65) [defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at editor.ui$make_menu_item$fn__10322.invoke(ui.clj:792) [defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at editor.ui$make_menu_command$reify__10309.handle(ui.clj:748) [defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.control.MenuItem.fire(MenuItem.java:462) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405) [jfxrt.jar:na]
	at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) [jfxrt.jar:na]
	at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) ~[jfxrt.jar:na]
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) ~[jfxrt.jar:na]
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) ~[jfxrt.jar:na]
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555) ~[jfxrt.jar:na]
	at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]

Defold version: 1.2.95
Defold sha: a89c5c502c53dae7788f2781bba29685e166d1d2
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by Malmer** [comment]
This is a new bug, because I think this used to work, but doesn't now. I have a collection with this very setup that I have created. But I can't do it again now.

**Comment by Malmer** [comment]
BLOCKER

**Comment by RagnarSvenssonKing** [comment]
What can I say, it's really embarrassing. So sorry about this.

**Comment by RagnarSvenssonKing** [comment]
It also means I'm fixing it NOW.
