### ISSUE TITLE
class java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by sofiahe** [defold/editor2-issues#301]
One time i moved a folder with images trying to replace another folder with same name.

Next time i clicked Sync.

clojure.core$_cache_protocol_fn.invokeStatic.class java.lang.IllegalArgumentException: No implementation of method: :proj-path of protocol: #'editor.resource/Resource found for class: nil
    at clojure.core$_cache_protocol_fn.invokeStatic(core_deftype.clj:568)
    at editor.resource$fn__7898$G__7827__7903.invoke(resource.clj:18)
    at editor.atlas$fn__38261.invokeStatic(atlas.clj:124)
    at editor.atlas$fn__38261.invoke(atlas.clj:124)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:379)
    at editor.atlas$AtlasImage$behavior$path.invokeStatic(atlas.clj:124)
    at editor.atlas$AtlasImage$behavior$path.invoke(atlas.clj:124)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.atlas$AtlasImage$behavior$id.invokeStatic(atlas.clj:124)
    at editor.atlas$AtlasImage$behavior$id.invoke(atlas.clj:124)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn__4474.invoke(node.clj:1112)
    at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
    at clojure.core$reduce.invokeStatic(core.clj:6544)
    at clojure.core$mapv.invokeStatic(core.clj:6618)
    at internal.node$pull_input_values.invokeStatic(node.clj:1113)
    at editor.atlas$AtlasNode$behavior$anim_ids.invokeStatic(atlas.clj:378)
    at editor.atlas$AtlasNode$behavior$anim_ids.invoke(atlas.clj:378)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1096)
    at editor.sprite$SpriteNode$behavior$default_animation.invokeStatic(sprite.clj:225)
    at editor.sprite$SpriteNode$behavior$default_animation.invoke(sprite.clj:225)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.sprite$SpriteNode$behavior$save_data.invokeStatic(sprite.clj:225)
    at editor.sprite$SpriteNode$behavior$save_data.invoke(sprite.clj:225)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1096)
    at editor.game_object$EmbeddedComponent$behavior$rt_ddf_message.invokeStatic(game_object.clj:149)
    at editor.game_object$EmbeddedComponent$behavior$rt_ddf_message.invoke(game_object.clj:149)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.game_object$EmbeddedComponent$behavior$ddf_message.invokeStatic(game_object.clj:149)
    at editor.game_object$EmbeddedComponent$behavior$ddf_message.invoke(game_object.clj:149)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn__4474.invoke(node.clj:1112)
    at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
    at clojure.core$reduce.invokeStatic(core.clj:6544)
    at clojure.core$mapv.invokeStatic(core.clj:6618)
    at internal.node$pull_input_values.invokeStatic(node.clj:1113)
    at editor.game_object$GameObjectNode$behavior$proto_msg.invokeStatic(game_object.clj:307)
    at editor.game_object$GameObjectNode$behavior$proto_msg.invoke(game_object.clj:307)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_first_input_value.invokeStatic(node.clj:1096)
    at editor.collection$EmbeddedGOInstanceNode$behavior$ddf_message.invokeStatic(collection.clj:223)
    at editor.collection$EmbeddedGOInstanceNode$behavior$ddf_message.invoke(collection.clj:223)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn__4474.invoke(node.clj:1112)
    at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
    at clojure.core$reduce.invokeStatic(core.clj:6544)
    at clojure.core$mapv.invokeStatic(core.clj:6618)
    at internal.node$pull_input_values.invokeStatic(node.clj:1113)
    at editor.collection$CollectionNode$behavior$proto_msg.invokeStatic(collection.clj:444)
    at editor.collection$CollectionNode$behavior$proto_msg.invoke(collection.clj:444)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at editor.collection$CollectionNode$behavior$save_data.invokeStatic(collection.clj:444)
    at editor.collection$CollectionNode$behavior$save_data.invoke(collection.clj:444)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$pull_input_values$fn__4474.invoke(node.clj:1112)
    at clojure.core$mapv$fn__6953.invoke(core.clj:6627)
    at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
    at clojure.core$reduce.invokeStatic(core.clj:6544)
    at clojure.core$mapv.invokeStatic(core.clj:6618)
    at internal.node$pull_input_values.invokeStatic(node.clj:1113)
    at editor.defold_project$Project$behavior$save_data.invokeStatic(defold_project.clj:412)
    at editor.defold_project$Project$behavior$save_data.invoke(defold_project.clj:412)
    at clojure.lang.Var.invoke(Var.java:383)
    at internal.node.NodeImpl.produce_value(node.clj:271)
    at internal.node$node_value_STAR_.invokeStatic(node.clj:338)
    at internal.node$node_value.invokeStatic(node.clj:353)
    at dynamo.graph$node_value.invokeStatic(graph.clj:739)
    at editor.defold_project$write_save_data_to_disk_BANG_.invokeStatic(defold_project.clj:165)
    at editor.defold_project$save_all_BANG_$fn__12101$fn__12102.invoke(defold_project.clj:213)
    at editor.defold_project$save_all_BANG_$fn__12101.invoke(defold_project.clj:213)
    at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938)
    at clojure.lang.AFn.call(AFn.java:18)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

<hr/>
Defold version: 1.2.95
Defold sha: 5b775cc05bba55fa7b6c1df238a0671469a92bb8
Platform: Windows 7 6.1 (amd64)
Java version: 1.8.0_102-b14

**Comment by ragnard-king** [comment]
Can't repro this one so closing, but found another sync-related issue in https://github.com/defold/editor2-issues/issues/352.
