### ISSUE TITLE
Auto update fails

### ISSUE THREAD

**Issue by britzl** [defold/editor2-issues#319]
Automatic update fails.

Running version a89c5c502c53dae7788f2781bba29685e166d1d2
Mac OSX Sierra

No update message in editor and no error except in the log:

2016-12-13 08:46:22.173 20329 [Timer-0] INFO  com.defold.editor.Updater - downloading config -> /var/folders/p_/1w8ksqx539l7s_dw6ppntdvw0000gp/T/8056244510926625855/6289922909266493643.tmp
2016-12-13 08:46:22.243 20399 [Timer-0] INFO  com.defold.editor.Updater - copying /var/folders/p_/1w8ksqx539l7s_dw6ppntdvw0000gp/T/8056244510926625855/7763003904810753196.tmp -> /private/var/folders/p_/1w8ksqx539l7s_dw6ppntdvw0000gp/T/AppTranslocation/CE8D6667-7F06-4F07-9EFF-C9BC6F2A0415/d/Defold.app/Contents/Resources/packages/defold-6281048b5c90f95c4ec2973b1b9c8f8e7f3c0b9c.jar
2016-12-13 08:46:22.248 20404 [Timer-0] DEBUG com.defold.editor.Start - update failed
java.io.FileNotFoundException: /private/var/folders/p_/1w8ksqx539l7s_dw6ppntdvw0000gp/T/AppTranslocation/CE8D6667-7F06-4F07-9EFF-C9BC6F2A0415/d/Defold.app/Contents/Resources/packages/defold-6281048b5c90f95c4ec2973b1b9c8f8e7f3c0b9c.jar (Read-only file system)
        at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_102]
        at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_102]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_102]
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_102]
        at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1139) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
        at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
        at com.defold.editor.Updater.copyFile(Updater.java:66) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
        at com.defold.editor.Updater.apply(Updater.java:79) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
        at com.defold.editor.Updater.check(Updater.java:124) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
        at com.defold.editor.Start$1.run(Start.java:119) ~[defold-a89c5c502c53dae7788f2781bba29685e166d1d2.jar:na]
        at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_102]
        at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_102]

**Comment by RagnarSvenssonKing** [comment]
I checked the hard drive of the affected machine and the app sits in /private/var/folders/p_/1w8ksqx539l7s_dw6ppntdvw0000gp/T/AppTranslocation/CE8D6667-7F06-4F07-9EFF-C9BC6F2A0415/d/Defold.app, which is indeed a read-only directory. The question is how the app was started from that directory, rather than Downloads. A wild guess is that this could be the result of a timing thing, where the browser or OSX has temporarily stored it in that location and the user managed to run it from there. We need to investigate this more, maybe by trying to open the .zip from within the browser before the download has completed, or just google it.

**Comment by britzl** [comment]
Obsolete.
