### ISSUE TITLE
Concurrent modification of graph when saving

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#353]
### Expected behaviour

No exception.

### Actual behaviour

clojure.lang.ExceptionInfo: Concurrent modification of graph

### Steps to reproduce

Hard to repro. I *think* I saved and tabbed in/out of application in quick succession.

<hr/>

<table>
<tr><td>Defold version</td><td>dev</td></tr>
<tr><td>Defold sha</td><td></td></tr>
<tr><td>Build time</td><td></td></tr>
<tr><td>OS name</td><td>Mac OS X</td></tr>
<tr><td>OS version</td><td>10.11.6</td></tr>
<tr><td>OS arch</td><td>x86_64</td></tr>
<tr><td>Java version</td><td>1.8.0_101-b13</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=4216940fdfac4363ab61bfd8b5307c2c'>4216940fdfac4363ab61bfd8b5307c2c</a></td></tr>
<table>

**Comment by tarnumius** [comment]
Confirm - after some worktime and press Ctrl+S receieve error
clojure.lang.ExceptionInfo: Concurrent modification of graph
log

2017-01-27 16:31:09.061 649920 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 86}
clojure.lang.ExceptionInfo: Concurrent modification of graph
	at clojure.core$ex_info.invokeStatic(core.clj:4617) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at dynamo.graph$merge_graphs.invokeStatic(graph.clj:98) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at dynamo.graph$transact$fn__5721.invoke(graph.clj:147) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at clojure.lang.LockingTransaction.run(LockingTransaction.java:273) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at clojure.lang.LockingTransaction.runInTransaction(LockingTransaction.java:229) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at dynamo.graph$transact.invokeStatic(graph.clj:146) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at dynamo.graph$set_property_BANG_.invokeStatic(graph.clj:594) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:208) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at editor.defold_project$write_save_data_to_disk_BANG_.invokeStatic(defold_project.clj:175) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at editor.defold_project$save_all_BANG_$fn__12544$fn__12545.invoke(defold_project.clj:222) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at editor.defold_project$save_all_BANG_$fn__12544.invoke(defold_project.clj:222) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at clojure.core$binding_conveyor_fn$fn__4676.invoke(core.clj:1938) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at clojure.lang.AFn.call(AFn.java:18) ~[defold-f32230d96b986616b742218d7f1a5bce26519b2e.jar:na]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_102]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_102]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]

**Comment by ragnard-king** [comment]
@tarnumius A fix for this bug was merged yesterday and should be available in updates. Can you try updating and see if you are no longer able to re-produce? You can check Help -> About and "Build time" to see when your version was built.

**Comment by tarnumius** [comment]
@ragnard-king ohh thank you test new build.
