### ISSUE TITLE
I add new TileSource and recieve error

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#459]
### Expected behaviour
Not present error
### Actual behaviour
Recieve error java.lang.NullPointerException: Unknown
### Steps to reproduce
Create new TileSource
<hr/>

2017-02-07 00:05:44.368 731573 [JavaFX Application Thread] ERROR editor.error-reporting - {:line 86}
java.lang.NullPointerException: null
	at clojure.lang.RT.intCast(RT.java:1177) ~[defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at editor.scene$update_image_view_BANG_.invokeStatic(scene.clj:601) ~[defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at editor.scene$make_gl_pane_BANG_$fn__29406$fn__29411.invoke(scene.clj:669) ~[defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at editor.ui$__GT_timer$fn__11062.invoke(ui.clj:1288) ~[defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at editor.ui.proxy$javafx.animation.AnimationTimer$ff19274a.handle(Unknown Source) [defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.lambda$handle$484(AnimationTimer.java:57) [jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
	at javafx.animation.AnimationTimer$AnimationTimerReceiver.handle(AnimationTimer.java:56) [jfxrt.jar:na]
	at com.sun.scenario.animation.AbstractMasterTimer.timePulseImpl(AbstractMasterTimer.java:357) ~[jfxrt.jar:na]
	at com.sun.scenario.animation.AbstractMasterTimer$MainLoop.run(AbstractMasterTimer.java:267) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:506) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoopImpl(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._enterNestedEventLoop(WinApplication.java:218) ~[jfxrt.jar:na]
	at com.sun.glass.ui.Application.enterNestedEventLoop(Application.java:511) ~[jfxrt.jar:na]
	at com.sun.glass.ui.EventLoop.enter(EventLoop.java:107) ~[jfxrt.jar:na]
	at com.sun.javafx.tk.quantum.QuantumToolkit.enterNestedEventLoop(QuantumToolkit.java:583) ~[jfxrt.jar:na]
	at javafx.stage.Stage.showAndWait(Stage.java:474) ~[jfxrt.jar:na]
	at editor.ui$show_and_wait_BANG_.invokeStatic(ui.clj:282) ~[defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at editor.dialogs$make_error_dialog.invokeStatic(dialogs.clj:166) ~[defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at editor.boot$notify_user$fn__77283.invoke(boot.clj:140) ~[defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at editor.ui$do_run_now$fn__9926.invoke(ui.clj:169) ~[defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at clojure.lang.AFn.run(AFn.java:22) ~[defold-cbe022a4048da88be54c8e6136db54bdfd94ecdc.jar:na]
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295) ~[jfxrt.jar:na]
	at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294) ~[jfxrt.jar:na]
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method) ~[jfxrt.jar:na]
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191) ~[jfxrt.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]

<table>
<tr><td>Defold version</td><td>1.2.96</td></tr>
<tr><td>Defold sha</td><td>cbe022a4048da88be54c8e6136db54bdfd94ecdc</td></tr>
<tr><td>Build time</td><td>2017-02-06T18:38:26.480507</td></tr>
<tr><td>OS name</td><td>Windows 7</td></tr>
<tr><td>OS version</td><td>6.1</td></tr>
<tr><td>OS arch</td><td>amd64</td></tr>
<tr><td>Java version</td><td>1.8.0_102-b14</td></tr>
<tr><td>Error</td><td><a href='https://sentry.io/defold/editor2/?query=c85c9346b1b54814a9cd100965efa6b3'>c85c9346b1b54814a9cd100965efa6b3</a></td></tr>
<table>

**Comment by tarnumius** [comment]
Second question - i press space and not open palette from tile source on tile map
Third - how i can move scene in Editor 1 it can with press Alt+Mid Button Mouse

**Comment by ragnard-king** [comment]
Thanks for the report, we'll investigate.

Regarding your other questions:
2. You can show the palette using `Scene -> Tile Map -> Show Palette`.
3. You can pan scene using `Ctrl+Alt+Middle Mouse Button`, but we have an open issue to improve this: https://github.com/defold/editor2-issues/issues/183

**Comment by tarnumius** [comment]
Thank you for answer.

**Comment by ragnard-king** [comment]
Fix merged, coming in updated shortly.
