### ISSUE TITLE
[DEFEDIT-772] Automatic updates failed

### ISSUE THREAD

**Issue by ragnard-king** [defold/editor2-issues#475]
Update failed because it couldn't copy new JAR into packages directory:

```
2017-02-09 11:43:05.375 1841 [Timer-0] INFO  com.defold.editor.Updater - new version found 386493886a9934ae1dd2544a65cfab1daed09225
2017-02-09 11:43:05.376 1842 [Timer-0] INFO  com.defold.editor.Updater - downloading defold-386493886a9934ae1dd2544a65cfab1daed09225.jar -> /var/folders/vj/pc79pgt92130mqt6dyg4w6tw0000gp/T/6852522802261211402/676632414546309772.tmp
2017-02-09 11:43:41.922 38388 [Timer-0] INFO  com.defold.editor.Updater - downloading config -> /var/folders/vj/pc79pgt92130mqt6dyg4w6tw0000gp/T/6852522802261211402/1257680569247649421.tmp
2017-02-09 11:43:42.015 38481 [Timer-0] INFO  com.defold.editor.Updater - copying /var/folders/vj/pc79pgt92130mqt6dyg4w6tw0000gp/T/6852522802261211402/676632414546309772.tmp -> /private/var/folders/vj/pc79pgt92130mqt6dyg4w6tw0000gp/T/AppTranslocation/99C8679F-3C11-4172-A6AF-6DEA50A950D9/d/Defold.app/Contents/Resources/packages/defold-386493886a9934ae1dd2544a65cfab1daed09225.jar
2017-02-09 11:43:42.019 38485 [Timer-0] DEBUG com.defold.editor.Start - update failed
java.io.FileNotFoundException: /private/var/folders/vj/pc79pgt92130mqt6dyg4w6tw0000gp/T/AppTranslocation/99C8679F-3C11-4172-A6AF-6DEA50A950D9/d/Defold.app/Contents/Resources/packages/defold-386493886a9934ae1dd2544a65cfab1daed09225.jar (Read-only file system)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_102]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_102]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_102]
	at org.apache.commons.io.FileUtils.doCopyFile(FileUtils.java:1139) ~[defold-2fd8732d146f5a252125ce1b210e3793f50e169c.jar:na]
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1091) ~[defold-2fd8732d146f5a252125ce1b210e3793f50e169c.jar:na]
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038) ~[defold-2fd8732d146f5a252125ce1b210e3793f50e169c.jar:na]
	at com.defold.editor.Updater.copyFile(Updater.java:66) ~[defold-2fd8732d146f5a252125ce1b210e3793f50e169c.jar:na]
	at com.defold.editor.Updater.apply(Updater.java:79) ~[defold-2fd8732d146f5a252125ce1b210e3793f50e169c.jar:na]
	at com.defold.editor.Updater.check(Updater.java:124) ~[defold-2fd8732d146f5a252125ce1b210e3793f50e169c.jar:na]
	at com.defold.editor.Start$1.run(Start.java:119) ~[defold-2fd8732d146f5a252125ce1b210e3793f50e169c.jar:na]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_102]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_102]
```

**Comment by ragnard-king** [comment]
This is caused by a new feature in macOS Sierra called Gatekeeper Path Randomization (http://lapcatsoftware.com/articles/app-translocation.html) in which applications launched from `~/Downloads` will be copied to a read-only location before execution. This breaks our updater. We should check if we're running in a read-only setting and tell the user.

**Comment by ragnard-king** [comment]
@jakob-pogulis-king tells me this will go away if we create and sign a DMG instead. Might still want to improve how we handle failure in update operation.

**Comment by ragnard-king** [comment]
We're now creating signed DMGs for macOS so once those are in use this should no longer be an issue.
