### ISSUE TITLE
You can say update check url

### ISSUE THREAD

**Issue by tarnumius** [defold/editor2-issues#498]
I cannot update editor on work, because some network issues. Can you say check update url for manual check update and download full pack. Thank you.

**Comment by ragnard-king** [comment]
Hi! I can send you a new link on the forum, but I'd also like to understand why the automatic updates fail at your work. All we do when updating is an HTTP request to port 80 on a server hosting the update, and download some files. Do you know what is preventing that from working?

**Comment by tarnumius** [comment]
Send please thank you. 

I recieve this in log
2017-02-14 10:48:06.157 33366 [Timer-0] DEBUG com.defold.editor.Start - update check failed
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_102]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_102]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_102]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_102]
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246) ~[na:1.8.0_102]
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286) ~[na:1.8.0_102]
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345) ~[na:1.8.0_102]
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:704) ~[na:1.8.0_102]
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536) ~[na:1.8.0_102]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441) ~[na:1.8.0_102]
	at java.net.URL.openStream(URL.java:1045) ~[na:1.8.0_102]
	at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1460) ~[defold-0ffa70f89359fc87d77290be7ebe56f75e583762.jar:na]
	at com.defold.editor.Updater.download(Updater.java:97) ~[defold-0ffa70f89359fc87d77290be7ebe56f75e583762.jar:na]
	at com.defold.editor.Updater.check(Updater.java:131) ~[defold-0ffa70f89359fc87d77290be7ebe56f75e583762.jar:na]
	at com.defold.editor.Start$1.run(Start.java:127) ~[defold-0ffa70f89359fc87d77290be7ebe56f75e583762.jar:na]
	at java.util.TimerThread.mainLoop(Timer.java:555) [na:1.8.0_102]
	at java.util.TimerThread.run(Timer.java:505) [na:1.8.0_102]

But 80 port not close on my computer and it relly strange. I try use vpn not help. On our NAT all ports open too.

**Comment by tarnumius** [comment]
Btw, can you make user_config file for override standart config some settings? After each update I need edit config log and vmargs and its small annoying
