### ISSUE TITLE
JSON resource support

### ISSUE THREAD

**Issue by mathiaswking** [defold/editor2-issues#53]
When opening a project with an invalid json file, it outputs errors to the command prompt (see below)

Example of bad json, which contains numbers instead of strings as indices:

{
  1 : { "pos" : "176,528,0", "offset" : "-5.3461656570435,-7.1796560287476,0", "speed" : "0" },
  2 : { "pos" : "208,560,0", "offset" : "0,0,0", "speed" : "0" },
  3 : { "pos" : "240,560,0", "offset" : "-5.3461656570435,-7.1796560287476,0", "speed" : "157.25139312744" },
  4 : { "pos" : "432,560,0", "offset" : "4.2453198432922,-5.296028137207,0", "speed" : "149.82375640869" },
  5 : { "pos" : "464,528,0", "offset" : "0,0,0", "speed" : "0" },
  6 : { "pos" : "464,496,0", "offset" : "-15.708464622498,33.985126495361,0", "speed" : "151.77278045654" },
  7 : { "pos" : "464,304,0", "offset" : "-2.7449645996094,-3.4814219474792,0", "speed" : "70.691269308128" },
  8 : { "pos" : "432,272,0", "offset" : "28.096813201904,-22.065999984741,0", "speed" : "85.016856350332" },
  9 : { "pos" : "400,272,0", "offset" : "-9.4541702270508,5.0533595085144,0", "speed" : "80.282249990712" },
  10 : { "pos" : "208,272,0", "offset" : "0,0,0", "speed" : "0" },
  11 : { "pos" : "176,304,0", "offset" : "0,0,0", "speed" : "0" },
  12 : { "pos" : "176,336,0", "offset" : "0,0,0", "speed" : "0" }
}

It would be nice if this was shown in the json editor instead.

Error log:
java.lang.Exception: JSON error (non-string key in object)
    at clojure.data.json$read_object.invokeStatic(json.clj:95) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$_read.invokeStatic(json.clj:207) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$read.invokeStatic(json.clj:264) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$read.doInvoke(json.clj:228) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:410) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyToHelper(AFn.java:154) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.applyTo(RestFn.java:132) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$apply.invokeStatic(core.clj:648) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$read_str.invokeStatic(json.clj:274) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$read_str.doInvoke(json.clj:274) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:410) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.json$load_json.invokeStatic(json.clj:36) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.json$load_json.invoke(json.clj:35) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_node.invokeStatic(defold_project.clj:72) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_resource_nodes$iter__16216__16220$fn__16221$fn__16222.invoke(defold_project.clj:87) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_resource_nodes$iter__16216__16220$fn__16221.invoke(defold_project.clj:83) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.LazySeq.sval(LazySeq.java:40) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.LazySeq.seq(LazySeq.java:49) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RT.seq(RT.java:521) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$seq__4357.invokeStatic(core.clj:137) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$dorun.invokeStatic(core.clj:3024) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$doall.invokeStatic(core.clj:3039) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_resource_nodes.invokeStatic(defold_project.clj:83) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:90) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$add_resources.invokeStatic(defold_project.clj:436) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$handle_resource_changes$fn__16654.invoke(defold_project.clj:490) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyToHelper(AFn.java:152) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyTo(AFn.java:144) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$apply.invokeStatic(core.clj:646) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:425) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:478) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:722) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:240) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:199) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:205) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:199) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:201) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.changes_view$fn__65166$fnk65161_positional__65167.invoke(changes_view.clj:55) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.changes_view$fn__65166$fnk65161__65186$fn__65187.invoke(changes_view.clj:50) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.changes_view$fn__65166$fnk65161__65186.invoke(changes_view.clj:50) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyToHelper(AFn.java:154) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyTo(AFn.java:144) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:408) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:25) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.handler$run.invokeStatic(handler.clj:40) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.ui$make_menu_command$reify__9621.handle(ui.clj:640) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [jfxrt.jar:na]
    at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
    at javafx.scene.control.MenuItem.fire(MenuItem.java:462) [jfxrt.jar:na]
    at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405) [jfxrt.jar:na]
    at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358) [jfxrt.jar:na]
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:na]
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) [jfxrt.jar:na]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) [jfxrt.jar:na]
    at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) ~[jfxrt.jar:na]
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) ~[jfxrt.jar:na]
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) ~[jfxrt.jar:na]
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) ~[jfxrt.jar:na]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380) ~[jfxrt.jar:na]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294) ~[jfxrt.jar:na]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416) ~[jfxrt.jar:na]
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389) ~[jfxrt.jar:na]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415) ~[jfxrt.jar:na]
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555) ~[jfxrt.jar:na]
    at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[jfxrt.jar:na]
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]
2016-09-15 14:04:02.738 WARN  default    editor.defold-project - {:line 76}
java.lang.Exception: JSON error (non-string key in object)
    at clojure.data.json$read_object.invokeStatic(json.clj:95) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$_read.invokeStatic(json.clj:207) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$read.invokeStatic(json.clj:264) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$read.doInvoke(json.clj:228) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:410) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyToHelper(AFn.java:154) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.applyTo(RestFn.java:132) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$apply.invokeStatic(core.clj:648) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$read_str.invokeStatic(json.clj:274) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.data.json$read_str.doInvoke(json.clj:274) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:410) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.json$load_json.invokeStatic(json.clj:36) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.json$load_json.invoke(json.clj:35) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_node.invokeStatic(defold_project.clj:72) ~[defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_resource_nodes$iter__16216__16220$fn__16221$fn__16222.invoke(defold_project.clj:87) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_resource_nodes$iter__16216__16220$fn__16221.invoke(defold_project.clj:83) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.LazySeq.sval(LazySeq.java:40) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.LazySeq.seq(LazySeq.java:49) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RT.seq(RT.java:521) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$seq__4357.invokeStatic(core.clj:137) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$dorun.invokeStatic(core.clj:3024) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$doall.invokeStatic(core.clj:3039) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_resource_nodes.invokeStatic(defold_project.clj:83) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$load_nodes_BANG_.invokeStatic(defold_project.clj:90) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$add_resources.invokeStatic(defold_project.clj:436) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$handle_resource_changes$fn__16654.invoke(defold_project.clj:490) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyToHelper(AFn.java:152) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyTo(AFn.java:144) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$apply.invokeStatic(core.clj:646) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:425) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project$handle_resource_changes.invokeStatic(defold_project.clj:478) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.defold_project.ProjectResourceListener.handle_changes(defold_project.clj:722) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:240) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:199) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:205) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invoke(workspace.clj:199) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.workspace$resource_sync_BANG_.invokeStatic(workspace.clj:201) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.changes_view$fn__65166$fnk65161_positional__65167.invoke(changes_view.clj:55) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.changes_view$fn__65166$fnk65161__65186$fn__65187.invoke(changes_view.clj:50) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.changes_view$fn__65166$fnk65161__65186.invoke(changes_view.clj:50) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyToHelper(AFn.java:154) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFn.applyTo(AFn.java:144) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at clojure.lang.RestFn.invoke(RestFn.java:408) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.handler$invoke_fnk.invokeStatic(handler.clj:25) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.handler$run.invokeStatic(handler.clj:40) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at editor.ui$make_menu_command$reify__9621.handle(ui.clj:640) [defold-34fa0bb2177263752ad104dc8b30fa2b5a948e79.jar:na]
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86) [jfxrt.jar:na]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49) [jfxrt.jar:na]
    at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
    at javafx.scene.control.MenuItem.fire(MenuItem.java:462) [jfxrt.jar:na]
    at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.doSelect(ContextMenuContent.java:1405) [jfxrt.jar:na]
    at com.sun.javafx.scene.control.skin.ContextMenuContent$MenuItemContainer.lambda$createChildren$343(ContextMenuContent.java:1358) [jfxrt.jar:na]
    at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218) ~[jfxrt.jar:na]
    at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80) [jfxrt.jar:na]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238) [jfxrt.jar:na]
    at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191) [jfxrt.jar:na]
    at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59) ~[jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56) [jfxrt.jar:na]
    at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114) [jfxrt.jar:na]
    at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74) [jfxrt.jar:na]
    at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54) [jfxrt.jar:na]
    at javafx.event.Event.fireEvent(Event.java:198) [jfxrt.jar:na]
    at javafx.scene.Scene$MouseHandler.process(Scene.java:3757) ~[jfxrt.jar:na]
    at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485) ~[jfxrt.jar:na]
    at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762) ~[jfxrt.jar:na]
    at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494) ~[jfxrt.jar:na]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:380) ~[jfxrt.jar:na]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:294) ~[jfxrt.jar:na]
    at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_102]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$354(GlassViewEventHandler.java:416) ~[jfxrt.jar:na]
    at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:389) ~[jfxrt.jar:na]
    at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:415) ~[jfxrt.jar:na]
    at com.sun.glass.ui.View.handleMouseEvent(View.java:555) ~[jfxrt.jar:na]
    at com.sun.glass.ui.View.notifyMouse(View.java:937) ~[jfxrt.jar:na]
    at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method) ~[jfxrt.jar:na]
    at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139) ~[jfxrt.jar:na]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_102]

**Comment by britzl** [comment]
Works now.
